"""
49_build_demand.py -- Phase 2I: where the people and the cars actually are.

    python scripts/phase2/49_build_demand.py

Until now the crowd density scaled with how much pavement happened to be in
view and traffic density with how many lanes were in scope. That is backwards
in the most visible possible way: Times Square came back with 243 pedestrians
and a SoHo side street with 445, because SoHo has more small streets per
hectare than Times Square has.

Two demand fields fix it, both from measurements rather than taste.

Pedestrians, per 200 m cell
    Built from what PLUTO says is actually there -- retail floor area, office
    floor area, residential units -- because footfall is generated by floor
    space, not by pavement. Split into a daytime and an evening field so the
    Financial District can empty out after work while the East Village fills.

Vehicles, per street edge
    NYC DOT publishes hourly volume counts (7ym2-wayt): 343,555 Manhattan
    observations over 808 distinct segments. Those are joined to the LION
    graph geometrically -- the counts carry State Plane feet and no lat/lon,
    so scripts/phase2/nysp.py inverts EPSG:2263 -- and the 15,571 edges with
    no count get a fitted estimate whose usefulness is measured by holdout
    rather than assumed.

Writes
    data/manhattan/runtime/demand.json      per-cell pedestrian field
    data/manhattan/streets/street_demand.json  per-edge vehicle volume
    docs/phase2/DEMAND_REPORT.json
"""

import csv
import json
import math
import os
import random
import sys
import time
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)
import nysp  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
REG = os.path.join(ROOT, "data", "manhattan", "buildings")
STREETS = os.path.join(ROOT, "data", "manhattan", "streets")
RUNTIME = os.path.join(ROOT, "data", "manhattan", "runtime")
NYC = os.path.join(ROOT, "source_data", "nyc")
DOCS = os.path.join(ROOT, "docs", "phase2")

LAT0, LON0 = 40.7800, -73.9680
M_LAT = 110574.0
M_LON = 111320.0 * math.cos(math.radians(LAT0))

CELL = 200.0
SQFT = 0.092903          # PLUTO areas are square feet

# Trips generated per unit of floor space, per hour, at the peak of each
# period. These are shape parameters, not survey values: what matters is the
# ratio between them, which is what decides whether Midtown out-draws the
# Lower East Side. Retail dominates daytime footfall per square metre,
# offices generate a large but concentrated flow, housing a steady base.
W_DAY = {"retail": 0.055, "office": 0.011, "resid": 0.05, "other": 0.004}
W_EVE = {"retail": 0.038, "office": 0.002, "resid": 0.13, "other": 0.003}

SMOOTH = 1               # cells of blur; footfall spills across a block


def load_registry():
    path = os.path.join(REG, "building_registry.csv")
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if r.get("is_context") == "1":
                continue
            rows.append(r)
    return rows


def fnum(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


# PLUTO attributes describe a *tax lot*, not a building, and the registry
# copies them onto every building that matched that lot. Summing them per
# building therefore counts a lot once per building standing on it:
#
#     residential units   2,095,335  ->    730,806   (2.87x)
#     built floor area  324 M m2     ->  129 M m2    (2.51x)
#     office floor area  57.8 M m2   ->   36.0 M m2  (1.61x)
#
# Manhattan really has of the order of 870,000 housing units and 130 M m2 of
# floor space, so the per-lot figures are the credible ones. 20.6% of
# buildings share a lot with another, and they are disproportionately the
# large ones, which is why the error is so much bigger than 20%.
#
# Splitting a lot evenly would be almost as wrong -- a lot with a 50-storey
# tower and a loading dock would put half its offices in the dock -- so the
# share is by approximate built volume, footprint times floors.
LOT_FIELDS = ("bldg_area", "res_area", "retail_area", "office_area",
              "factory_area", "garage_area", "units_res", "units_total",
              "lot_area")


def allocate_lot_attributes(rows):
    share = defaultdict(float)
    weights = []
    for r in rows:
        bbl = r.get("bbl") or ""
        fp = fnum(r.get("footprint_area"))
        fl = max(1.0, fnum(r.get("number_of_floors")) or
                 max(1.0, fnum(r.get("roof_height")) / 3.5))
        w = max(1.0, fp * fl)
        weights.append(w)
        if bbl:
            share[bbl] += w

    split = 0
    for r, w in zip(rows, weights):
        bbl = r.get("bbl") or ""
        tot = share.get(bbl, 0.0)
        # lot_area is a property of the lot itself, not something to divide,
        # but every floor-area and unit count is a total to apportion
        f = (w / tot) if tot > 0 else 1.0
        if f < 0.999:
            split += 1
        for k in LOT_FIELDS:
            if k == "lot_area":
                continue
            r[k] = fnum(r.get(k)) * f
    return split


# ---------------------------------------------------------------------------
# pedestrian field
# ---------------------------------------------------------------------------
def build_ped_field(rows):
    day = defaultdict(float)
    eve = defaultdict(float)
    parts = defaultdict(lambda: defaultdict(float))
    for r in rows:
        x, y = fnum(r.get("x_m")), fnum(r.get("y_m"))
        if not x and not y:
            continue
        key = (int(math.floor(x / CELL)), int(math.floor(y / CELL)))
        retail = fnum(r.get("retail_area")) * SQFT
        office = fnum(r.get("office_area")) * SQFT
        units = fnum(r.get("units_res"))
        total = fnum(r.get("bldg_area")) * SQFT
        other = max(0.0, total - retail - office -
                    fnum(r.get("res_area")) * SQFT)
        day[key] += (retail * W_DAY["retail"] + office * W_DAY["office"] +
                     units * W_DAY["resid"] + other * W_DAY["other"])
        eve[key] += (retail * W_EVE["retail"] + office * W_EVE["office"] +
                     units * W_EVE["resid"] + other * W_EVE["other"])
        parts[key]["retail_m2"] += retail
        parts[key]["office_m2"] += office
        parts[key]["units"] += units
        parts[key]["buildings"] += 1

    # A block's footfall does not stop at the cell boundary -- someone leaving
    # an office tower walks past the next three cells to reach the subway.
    def blur(field):
        out = defaultdict(float)
        for (cx, cy), v in field.items():
            for dx in range(-SMOOTH, SMOOTH + 1):
                for dy in range(-SMOOTH, SMOOTH + 1):
                    w = 1.0 / (1.0 + abs(dx) + abs(dy))
                    out[(cx + dx, cy + dy)] += v * w
        return out

    return blur(day), blur(eve), parts


# ---------------------------------------------------------------------------
# vehicle field
# ---------------------------------------------------------------------------
def seg_dist(px, py, a, b):
    dx, dy = b[0] - a[0], b[1] - a[1]
    d2 = dx * dx + dy * dy
    t = 0.0 if d2 < 1e-9 else max(0.0, min(1.0, ((px - a[0]) * dx +
                                                 (py - a[1]) * dy) / d2))
    return math.hypot(px - a[0] - t * dx, py - a[1] - t * dy)


def join_counts(graph, counts, max_snap=30.0):
    """Attach each DOT count point to the nearest LION edge."""
    grid = defaultdict(list)
    for e in graph["edges"]:
        for i in range(len(e["pts"]) - 1):
            a, b = e["pts"][i], e["pts"][i + 1]
            cx = int(((a[0] + b[0]) * 0.5) // CELL)
            cy = int(((a[1] + b[1]) * 0.5) // CELL)
            grid[(cx, cy)].append((a, b, e["id"]))

    per_edge = defaultdict(list)
    snapped = 0
    far = 0
    for c in counts:
        p = nysp.parse_point(c.get("wktgeom") or "")
        if not p:
            continue
        lon, lat = nysp.to_wgs84(*p)
        x, y = (lon - LON0) * M_LON, (lat - LAT0) * M_LAT
        cx, cy = int(x // CELL), int(y // CELL)
        best, best_id = 1e18, -1
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                for a, b, eid in grid.get((cx + dx, cy + dy), ()):
                    d = seg_dist(x, y, a, b)
                    if d < best:
                        best, best_id = d, eid
        if best_id < 0 or best > max_snap:
            far += 1
            continue
        try:
            v = float(c.get("v") or 0)
        except (TypeError, ValueError):
            continue
        if v <= 0:
            continue
        per_edge[best_id].append(v)
        snapped += 1
    # several count points and both directions can land on one edge
    return ({k: sum(v) / len(v) for k, v in per_edge.items()},
            {"points": len(counts), "snapped": snapped, "too_far": far,
             "edges_with_counts": len(per_edge)})


def fit_volume_model(graph, measured):
    """Predict average hourly volume for an edge that has no count.

    Fitted multiplicatively in log space on travel lanes and carriageway
    width, and then *checked*: a model that cannot beat predicting the global
    mean is not worth shipping, and this reports whether it does."""
    by_id = {e["id"]: e for e in graph["edges"]}
    data = [(by_id[k], v) for k, v in measured.items() if k in by_id]
    if len(data) < 40:
        return None, {"skipped": "too few measured edges"}

    rng = random.Random(20260804)
    idx = list(range(len(data)))
    rng.shuffle(idx)
    cut = int(len(idx) * 0.8)
    train = [data[i] for i in idx[:cut]]
    test = [data[i] for i in idx[cut:]]

    def bucket(e):
        lanes = max(1, min(6, int(e.get("lanes") or 1)))
        w = e.get("width") or 12.8
        wb = 0 if w < 11 else (1 if w < 16 else (2 if w < 19 else 3))
        return (lanes, wb)

    def fit(rows):
        grand = sum(math.log(v) for _, v in rows) / len(rows)
        cells = defaultdict(list)
        for e, v in rows:
            cells[bucket(e)].append(math.log(v))
        # shrink small buckets toward the grand mean
        table = {}
        for k, vs in cells.items():
            n = len(vs)
            table[k] = (sum(vs) + 4.0 * grand) / (n + 4.0)
        return grand, table

    grand, table = fit(train)

    def predict(e):
        return math.exp(table.get(bucket(e), grand))

    def err(rows, fn):
        return sorted(abs(math.log(fn(e)) - math.log(v)) for e, v in rows)

    e_model = err(test, predict)
    e_base = err(test, lambda e: math.exp(grand))
    med_m = e_model[len(e_model) // 2]
    med_b = e_base[len(e_base) // 2]

    grand_all, table_all = fit(data)

    def predict_all(e):
        return math.exp(table_all.get(bucket(e), grand_all))

    stats = {
        "train": len(train), "test": len(test),
        "median_log_error_model": round(med_m, 4),
        "median_log_error_mean_baseline": round(med_b, 4),
        # exp(median log error) reads as "typically within a factor of x"
        "typical_factor_model": round(math.exp(med_m), 2),
        "typical_factor_baseline": round(math.exp(med_b), 2),
        "beats_baseline": bool(med_m < med_b),
        "buckets": len(table_all),
        "fallback_mean_vph": round(math.exp(grand_all), 1),
    }
    return (predict_all if med_m < med_b else
            (lambda e: math.exp(grand_all))), stats


def main():
    t0 = time.time()
    print("=" * 74)
    print("PHASE 2I  POPULATION AND TRAFFIC DEMAND")
    print("=" * 74)

    rows = load_registry()
    print("  registry        : %d Manhattan buildings" % len(rows))
    split = allocate_lot_attributes(rows)
    tot_units = sum(fnum(r.get("units_res")) for r in rows)
    tot_office = sum(fnum(r.get("office_area")) for r in rows) * SQFT
    tot_floor = sum(fnum(r.get("bldg_area")) for r in rows) * SQFT
    print("  lot allocation  : %d buildings share a lot; after split "
          "%.0f res units, %.1f M m2 office, %.0f M m2 floor area"
          % (split, tot_units, tot_office / 1e6, tot_floor / 1e6))
    day, eve, parts = build_ped_field(rows)
    print("  pedestrian field: %d cells" % len(day))

    graph = json.load(open(os.path.join(STREETS, "street_graph.json"),
                           encoding="utf-8"))
    cpath = os.path.join(NYC, "traffic_volume.json")
    if os.path.exists(cpath):
        counts = json.load(open(cpath, encoding="utf-8"))
    else:
        counts = []
        print("  !! no traffic_volume.json; run the fetch first")
    measured, jstat = join_counts(graph, counts)
    print("  DOT counts      : %s" % jstat)
    model, mstat = fit_volume_model(graph, measured)
    print("  volume model    : %s" % mstat)

    vol = {}
    est = 0
    for e in graph["edges"]:
        if not e.get("drivable"):
            continue
        if e["id"] in measured:
            vol[e["id"]] = [round(measured[e["id"]], 1), 1]
        elif model:
            vol[e["id"]] = [round(model(e), 1), 0]
            est += 1
    print("  edge volumes    : %d measured, %d estimated"
          % (len(measured), est))

    # normalise the pedestrian field to 0..1 on its 99th percentile, so one
    # freak cell cannot flatten the whole city
    def norm(field):
        vals = sorted(field.values())
        if not vals:
            return {}, 1.0
        top = vals[int(len(vals) * 0.99)] or 1.0
        return ({"%d,%d" % k: round(min(1.0, v / top), 4)
                 for k, v in field.items() if v > 0}, top)

    nday, top_d = norm(day)
    neve, top_e = norm(eve)

    os.makedirs(RUNTIME, exist_ok=True)
    with open(os.path.join(RUNTIME, "demand.json"), "w",
              encoding="utf-8") as f:
        json.dump({
            "generated_by": "scripts/phase2/49_build_demand.py",
            "cell_m": CELL,
            "source": "PLUTO floor areas and residential units via the "
                      "building registry",
            "scale": {"day_p99": round(top_d, 1), "eve_p99": round(top_e, 1)},
            "day": nday, "eve": neve,
        }, f, separators=(",", ":"))

    vals = sorted(v[0] for v in vol.values())
    vmax = vals[-1] if vals else 1.0
    # Normalise the runtime weight against a high percentile, not the maximum.
    # One segment of the FDR Drive carries 2,700 vehicles an hour and Manhattan
    # as a whole runs at 57; dividing by the maximum squeezed every ordinary
    # street into the 0.23-0.38 band and the weighting did nothing.
    vref = vals[int(len(vals) * 0.90)] if vals else 1.0
    with open(os.path.join(STREETS, "street_demand.json"), "w",
              encoding="utf-8") as f:
        json.dump({
            "generated_by": "scripts/phase2/49_build_demand.py",
            "source": "NYC DOT Traffic Volume Counts 7ym2-wayt, joined to "
                      "LION geometrically via EPSG:2263 inverse",
            "units": "mean vehicles per hour per segment, both directions",
            "max_vph": round(vmax, 1),
            "ref_vph": round(max(1.0, vref), 1),
            "measured_flag": "1 = observed, 0 = fitted from lanes and width",
            "volumes": {str(k): v for k, v in vol.items()},
        }, f, separators=(",", ":"))

    # what the field actually says -- the headline check
    named = []
    for k, v in sorted(day.items(), key=lambda kv: -kv[1])[:12]:
        cx, cy = k
        x, y = (cx + 0.5) * CELL, (cy + 0.5) * CELL
        lat, lon = y / M_LAT + LAT0, x / M_LON + LON0
        p = parts.get(k, {})
        named.append({"cell": "%d,%d" % k, "lat": round(lat, 5),
                      "lon": round(lon, 5), "day": round(v, 1),
                      "retail_m2": round(p.get("retail_m2", 0)),
                      "office_m2": round(p.get("office_m2", 0)),
                      "units": int(p.get("units", 0))})
    print("-" * 74)
    print("  busiest daytime cells:")
    for r in named[:8]:
        print("    %-12s %.5f %.5f  day %8.0f  retail %7d m2  office %8d m2"
              % (r["cell"], r["lat"], r["lon"], r["day"],
                 r["retail_m2"], r["office_m2"]))

    os.makedirs(DOCS, exist_ok=True)
    with open(os.path.join(DOCS, "DEMAND_REPORT.json"), "w",
              encoding="utf-8") as f:
        json.dump({
            "cells": len(day),
            "join": jstat,
            "volume_model": mstat,
            "edges_measured": len(measured),
            "edges_estimated": est,
            "max_vph": round(vmax, 1),
            "busiest_daytime_cells": named,
            "weights_day": W_DAY, "weights_eve": W_EVE,
            "seconds": round(time.time() - t0, 1),
        }, f, indent=1)
    print("  done in %.0fs" % (time.time() - t0))
    print("=" * 74)
    return 0


if __name__ == "__main__":
    sys.exit(main())
