// doors.js — Phase 3B: real doorways, cut into the buildings the hero
// corridor touches, and walk-in interiors with no keypress and no teleport.
//
// What this replaces: interiors.js's E-at-a-marked-threshold entry, which was
// honest about the geometry (the shells were solid) but is now the most
// visible piece of honesty debt left — the HANDOFF calls it out verbatim.
//
// What this does, per configured building:
//
//   1. Cut a real rectangular opening into the building's baked tile wall at
//      street level (exact 2D rect subtraction in the wall plane, doors-math).
//      The walk collider probes the actual tile meshes, so a real hole in the
//      mesh is a real hole in the collision: no hit filter, no fake doorway.
//   2. Punch the matching opening in the room's glazed entrance wall.
//   3. Build the door assembly in the opening: frame (jambs, header, sill),
//      an automatic sliding leaf with a glass pane, a header track, and a lit
//      ceiling panel over the threshold. All procedural, in the same palette
//      as the authored interiors — no third-party asset enters the build.
//   4. Run a door state machine per doorway: closed -> opening -> open ->
//      closing -> closed, driven by a trigger volume; an obstruction that
//      reopens a closing door; a dwell that lets the player pass; a pause
//      freeze; and persisted state across reloads.
//   5. Detect the player crossing the wall plane through the opening and flip
//      interiors.inside physically — the camera never jumps, and walking back
//      out reverses it (reverse traversal).
//   6. Preload the interior when the player is near the threshold: the room
//      group becomes visible and the interior lamp ramps up before the
//      threshold is crossed, so the walk-in is continuous and there is no
//      black void behind the opening.
//   7. Physical lift rides for the interior link thresholds (HQ lobby <->
//      Floor 45, home lobby <-> penthouse) in the corridor's own cab, so the
//      interior transitions that remain are rides, not teleports.
//
// The corridor buildings are configured in data-driven form
// (data/doors/doors.json, generated by scripts/phase2/68_build_doors.py) so
// the same pipeline can be pointed at the ~660 subway-adjacent and
// ground-floor-retail buildings later. Nothing here hard-codes a building.
//
// Verification lives in verify() (measured numbers, per HANDOFF §0) and the
// headless run in scripts/qa/doorcheck-run.mjs.

import * as THREE from 'three'
import {
  cutTriangle, fanTriangles, polyArea, rectsOverlap, polyBox,
  triNormal3, wallFrame, framePoint, frameProject,
} from './doors-math.js'

// ---- the authored room frame ----------------------------------------------
//
// Everything in this file is written in the *authored* room frame, the one
// 60_interiors.py builds in and the HANDOFF §4 documents: +x into the room,
// +y to the left along the entrance wall, +z up.
//
// That is NOT the room group's own local frame. The glTF exporter maps
// Blender (x, y, z) -> (x, z, -y), so the group's local axes are
// (x into the room, y up, z along the wall to the right), and
// interiors.place() keeps the conversion in exactly one place: room.local().
//
// Applying that swap zero times is P2-056 all over again, and it shipped
// here: doors.js fed authored vectors straight to group.localToWorld(), so
// "1.7 m up" became 1.7 m sideways. Measured, on all six rooms,
// room.local(0,0,1.7) and group.localToWorld(0,0,1.7) differed by exactly
// 1.70 m of height — which put every walk-in 1.70 m to the side of a 2.20 m
// opening, 0.60 m past its edge, walking into uncut wall. The trace: the
// camera pinned at room-local x = -0.721 m for 65 consecutive frames with
// the door fully open.
//
// So: authored coordinates cross into group space through authToLocal() and
// come back through localToAuth(), and nowhere else. The door assembly gets
// the same swap as a single -90 deg rotation about x on its own child group,
// which is the matrix form of (x, y, z) -> (x, z, -y).

// Authored (x into, y left, z up) -> room-group local (x into, y up, z right).
export function authToLocal(x, y, z, out) { return out.set(x, z, -y) }

// Room-group local -> authored.
export function localToAuth(v, out) { return out.set(v.x, -v.z, v.y) }

// The rotation that carries an authored-frame child into room-group space.
export const AUTHORED_ROT_X = -Math.PI / 2

// ---- doorway geometry (shared defaults; config can override) --------------
const WALL_W = 2.2          // opening cut in the building wall
const WALL_H = 2.5
const GLASS_W = 1.76        // opening cut in the room's glazed wall
const GLASS_H = 2.4
const GLASS_SILL = 0.22     // clear the authored threshold bar
const BAY_Y = 1.0           // room-local y of the door bay centre (between
                            // the authored mullion grid at 2 m pitch)
const LEAF_W = 1.76         // sliding leaf width (fits the glass opening)
const LEAF_H = 2.36
const LEAF_Z = 0.08         // leaf plane inset from the wall face
const SILL = 0.08
const TRACK_Z = 2.5         // header track height

// ---- door behaviour --------------------------------------------------------
const OPEN_S = 2.2          // leaf slide-out seconds
const CLOSE_S = 2.6
const DWELL_S = 3.5         // how long the door waits after the player leaves
const TRIGGER_X = [-2.3, 0.35]   // room-local x span of the trigger volume
const TRIGGER_MARGIN_Y = 0.95
const TRIGGER_Z = [-0.5, 3.2]
const OBSTRUCT_MARGIN = 0.45     // player body radius, applied to the leaf box
const PRELOAD_R = 9.0           // interior shown + lamp up inside this range
const CUT_R = 400.0             // wall cut applied once the player is this close
const APPROACH_R = 6.0          // the approach to a doorway must be this clear
const ENTER_MARGIN = 0.18       // crossing hysteresis at the wall plane
const WALL_GAP = 0.35           // room glazed wall sits this far inside the wall
const RECESS_WALL_DIST = 5.0    // HQ podium front, in front of the lobby glass

// ---- persistence -----------------------------------------------------------
const SAVE_KEY = 'manhattan.doors.v1'

// ---- palette, matching scripts/phase2/60_interiors.py ----------------------
const METAL = [0.145, 0.148, 0.152]
const WALL_DARK = [0.075, 0.072, 0.070]
const PANEL_LIT = [0.90, 0.88, 0.82]
const GLASS = [0.075, 0.090, 0.105]

// ---------------------------------------------------------------------------
// procedural mesh helpers (vertex-coloured boxes, in the house style)
// ---------------------------------------------------------------------------

function boxMesh(cx, cy, cz, sx, sy, sz, color, material) {
  const hx = sx * 0.5; const hy = sy * 0.5; const hz = sz * 0.5
  const corners = [
    [cx - hx, cy - hy, cz - hz], [cx + hx, cy - hy, cz - hz],
    [cx + hx, cy + hy, cz - hz], [cx - hx, cy + hy, cz - hz],
    [cx - hx, cy - hy, cz + hz], [cx + hx, cy - hy, cz + hz],
    [cx + hx, cy + hy, cz + hz], [cx - hx, cy + hy, cz + hz],
  ]
  const quads = [
    [3, 2, 1, 0], [5, 6, 7, 4], [1, 5, 4, 0],
    [2, 6, 5, 1], [3, 7, 6, 2], [0, 4, 7, 3],
  ]
  const positions = []
  const colors = []
  for (const q of quads) {
    for (const i of q) {
      positions.push(...corners[i])
      colors.push(...color)
    }
  }
  const g = new THREE.BufferGeometry()
  g.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3))
  g.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3))
  g.computeVertexNormals()
  const m = new THREE.Mesh(g, material)
  m.castShadow = false
  m.receiveShadow = true
  return m
}

// ---------------------------------------------------------------------------
// mesh cutting
// ---------------------------------------------------------------------------

// Remove only the triangles lying *wholly* inside `box` — a containment test,
// never an AABB-overlap test. Overlap is what the first pass of this file did
// and it is far too coarse against merged tile geometry, where one triangle
// can be a whole ground-to-roof wall quad: a face that merely reaches into
// the doorway volume (a neighbour's wall running past it) must keep its
// geometry, and only what is actually in the way comes out. `allow(bid)`
// gates which building ids may be removed.
export function cutContained(geometry, box, allow = () => true) {
  const pos = geometry.attributes.position
  const bidAttr = geometry.attributes._bid || geometry.attributes._BID
  const idx = geometry.index
  const tris = idx ? idx.count / 3 : pos.count / 3
  const keep = []
  let removed = 0
  for (let t = 0; t < tris; t++) {
    const a = idx ? idx.getX(t * 3) : t * 3
    const b = idx ? idx.getX(t * 3 + 1) : t * 3 + 1
    const c = idx ? idx.getX(t * 3 + 2) : t * 3 + 2
    let inside = true
    for (const i of [a, b, c]) {
      const x = pos.getX(i); const y = pos.getY(i); const z = pos.getZ(i)
      if (x < box.min[0] || x > box.max[0] || y < box.min[1] ||
          y > box.max[1] || z < box.min[2] || z > box.max[2]) {
        inside = false
        break
      }
    }
    if (inside && bidAttr && !allow(Math.round(bidAttr.getX(a)))) inside = false
    if (inside) removed++
    else keep.push([a, b, c])
  }
  if (!removed) return { geometry, removed: 0 }
  const out = cloneGeometry(geometry)
  const outIdx = []
  for (const [a, b, c] of keep) outIdx.push(a, b, c)
  out.setIndex(outIdx)
  out.computeBoundingSphere()
  return { geometry: out, removed }
}

// Punch a rectangular hole in a room's glazed entrance wall.
//
// The glaze is authored as a plane at the room's x ~ 0, so this is the same
// exact 2D rect subtraction the building wall gets (doors-math), done in the
// wall's own (u, v) = (mesh-local z along the wall, mesh-local y up).
//
// Dropping triangles by AABB cannot do this job. The lobby's glaze is a
// *single* 24 m quad, so removing every triangle whose AABB touches the door
// box deleted the entire pane — measured at 0 glaze triangles remaining on
// all four doorways, which is not a doorway, it is a missing wall. `rect` is
// in mesh-local (z, y);
// only faces within xMax of the entrance plane are considered, so a room
// whose glaze wraps a second wall keeps that wall.
export function cutGlazeRect(geometry, rect, xMax = 0.5) {
  const pos = geometry.attributes.position
  const idx = geometry.index
  const tris = idx ? idx.count / 3 : pos.count / 3
  const outTris = []
  const newVerts = []
  const newNorms = []
  const newCols = []
  const nrm = geometry.attributes.normal
  const col = geometry.attributes.color
  let cut = 0
  let removed = 0

  for (let t = 0; t < tris; t++) {
    const a = idx ? idx.getX(t * 3) : t * 3
    const b = idx ? idx.getX(t * 3 + 1) : t * 3 + 1
    const c = idx ? idx.getX(t * 3 + 2) : t * 3 + 2
    const xs = [pos.getX(a), pos.getX(b), pos.getX(c)]
    if (Math.max(...xs) > xMax) { outTris.push([a, b, c]); continue }
    // (u, v) = (along the wall, up)
    const tri = [
      [pos.getZ(a), pos.getY(a)],
      [pos.getZ(b), pos.getY(b)],
      [pos.getZ(c), pos.getY(c)],
    ]
    if (!rectsOverlap(polyBox(tri), rect)) { outTris.push([a, b, c]); continue }
    const pieces = cutTriangle(tri, rect)
    if (pieces === null) { outTris.push([a, b, c]); continue }
    if (!pieces.length) { removed++; continue }
    cut++

    // the entrance plane's x is whatever this face sits on (0.02 authored),
    // taken from the face itself so a slightly offset pane stays put
    const xPlane = (xs[0] + xs[1] + xs[2]) / 3
    const n0 = nrm ? [nrm.getX(a), nrm.getY(a), nrm.getZ(a)] : null
    const c0 = col ? [col.getX(a), col.getY(a), col.getZ(a)] : null
    const base = pos.count + newVerts.length / 3
    let k = 0
    for (const piece of pieces) {
      const off = k
      for (const [u, v] of piece) {
        newVerts.push(xPlane, v, u)
        if (n0) newNorms.push(n0[0], n0[1], n0[2])
        if (c0) newCols.push(c0[0], c0[1], c0[2])
        k++
      }
      for (let i = 1; i < piece.length - 1; i++) {
        outTris.push([base + off, base + off + i, base + off + i + 1])
      }
    }
  }

  if (!cut && !removed) return { geometry, cut: 0, removed: 0, kept: tris }
  const out = cloneGeometry(geometry)
  const nv = newVerts.length / 3
  extendAttribute(out.attributes.position, nv, (i) => newVerts[i])
  if (out.attributes.normal) {
    extendAttribute(out.attributes.normal, nv, (i) => newNorms[i] ?? 0)
  }
  if (out.attributes.color) {
    extendAttribute(out.attributes.color, nv, (i) => newCols[i] ?? 1)
  }
  for (const [name, attr] of Object.entries(out.attributes)) {
    if (name === 'position' || name === 'normal' || name === 'color') continue
    extendAttribute(attr, nv, null)
  }
  const outIdx = []
  for (const [a, b, c] of outTris) outIdx.push(a, b, c)
  out.setIndex(outIdx)
  out.computeBoundingSphere()
  out.computeBoundingBox()
  return { geometry: out, cut, removed, kept: outTris.length }
}

// Grow a BufferAttribute by `extra` items, filling from fillFn (index into
// the appended run) or with zeroes.
export function extendAttribute(attr, extra, fillFn) {
  const item = attr.itemSize
  const old = attr.array
  const arr = new (old.constructor)(old.length + extra * item)
  arr.set(old)
  for (let i = 0; i < extra * item; i++) {
    arr[old.length + i] = fillFn ? fillFn(i) : 0
  }
  attr.array = arr
  attr.count = arr.length / item
  attr.needsUpdate = true
  return attr
}

// Clone a geometry's attributes into a new geometry. The caller re-indexes.
export function cloneGeometry(geometry) {
  const out = new THREE.BufferGeometry()
  for (const [name, attr] of Object.entries(geometry.attributes)) {
    out.setAttribute(name, attr.clone())
  }
  return out
}

// Cut a rectangular doorway out of the wall faces of one building inside a
// merged tile mesh. `bidSet` maps vertex index -> belongs to the building
// (with .bid on it); `frame` is the wall frame (world); `rect` is the door
// rect in (u, v). Returns { geometry, cut, removed } — the new geometry, or
// the same geometry when nothing was cut. The appended split vertices copy
// the colour of the face they came from, so the facade shading is seamless.
export function cutWallInMesh(geometry, bidSet, frame, rect) {
  const pos = geometry.attributes.position
  const nrm = geometry.attributes.normal
  const col = geometry.attributes.color
  const idx = geometry.index
  const tris = idx ? idx.count / 3 : pos.count / 3

  const v = (i, out) => {
    out[0] = pos.getX(i); out[1] = pos.getY(i); out[2] = pos.getZ(i)
    return out
  }
  const p0 = [0, 0, 0]; const p1 = [0, 0, 0]; const p2 = [0, 0, 0]
  const outTris = []
  const newVerts = []
  const newNorms = []
  const newCols = []
  const newBids = []
  const srcBid = geometry.attributes._bid || geometry.attributes._BID
  let cut = 0
  let removed = 0

  for (let t = 0; t < tris; t++) {
    const a = idx ? idx.getX(t * 3) : t * 3
    const b = idx ? idx.getX(t * 3 + 1) : t * 3 + 1
    const c = idx ? idx.getX(t * 3 + 2) : t * 3 + 2
    if (!bidSet.has(a) || !bidSet.has(b) || !bidSet.has(c)) {
      outTris.push([a, b, c])
      continue
    }
    v(a, p0); v(b, p1); v(c, p2)
    const n = triNormal3(p0, p1, p2)
    const dot = n[0] * frame.normal[0] + n[1] * frame.normal[1] +
      n[2] * frame.normal[2]
    if (dot > -0.5) { outTris.push([a, b, c]); continue }
    const u0 = frameProject(frame, p0)
    const u1 = frameProject(frame, p1)
    const u2 = frameProject(frame, p2)
    const tb = polyBox([u0, u1, u2])
    if (!rectsOverlap(tb, rect)) { outTris.push([a, b, c]); continue }

    const pieces = cutTriangle([u0, u1, u2], rect)
    if (pieces === null) { outTris.push([a, b, c]); continue }
    if (!pieces.length) { removed++; continue }
    cut++

    // the piece vertices, fanned into triangles in (u, v)
    const flat = []
    const triIndex = []
    for (const piece of pieces) {
      const off = flat.length / 2
      for (const [u, vv] of piece) flat.push(u, vv)
      for (let i = 1; i < piece.length - 1; i++) {
        triIndex.push(off, off + i, off + i + 1)
      }
    }
    const base = pos.count + newVerts.length / 3
    const c0 = col ? [col.getX(a), col.getY(a), col.getZ(a)] : null
    // the face's own building id, not the caller's: a passage cut runs over
    // the *neighbours'* faces, and stamping them with the target's bid would
    // relabel another building's facade (Draco quantises _BID, so round it —
    // P2-060)
    const b0 = srcBid ? Math.round(srcBid.getX(a))
      : (bidSet.bid ?? 0)
    for (const i of triIndex) {
      const p = framePoint(frame, flat[i * 2], flat[i * 2 + 1])
      newVerts.push(p[0], p[1], p[2])
      newNorms.push(n[0], n[1], n[2])
      newBids.push(b0)
      if (c0) newCols.push(c0[0], c0[1], c0[2])
    }
    for (const i of triIndex) outTris.push([base + i, base + i + 1, base + i + 2])
  }

  if (!cut && !removed) return { geometry, cut: 0, removed: 0 }

  const out = cloneGeometry(geometry)
  const posA = out.attributes.position
  const nrmA = out.attributes.normal
  const colA = out.attributes.color
  const nv = newVerts.length / 3

  const extend = extendAttribute
  extend(posA, nv, (i) => newVerts[i])
  if (nrmA) extend(nrmA, nv, (i) => newNorms[i])
  if (colA) extend(colA, nv, (i) => newCols[i])
  const bidName = out.attributes._bid ? '_bid' : '_BID'
  if (bidName && out.attributes[bidName]) {
    extend(out.attributes[bidName], nv, (i) => newBids[i])
  }
  const other = []
  for (const [name, attr] of Object.entries(out.attributes)) {
    if (name === 'position' || name === 'normal' || name === 'color' ||
        name === bidName) continue
    other.push([name, attr])
  }
  for (const [name, attr] of other) extend(attr, nv, null)

  const outIdx = []
  for (const [a, b, c] of outTris) outIdx.push(a, b, c)
  out.setIndex(outIdx)
  out.computeBoundingSphere()
  return { geometry: out, cut, removed }
}

// ---------------------------------------------------------------------------
// the door system
// ---------------------------------------------------------------------------

export class Doors {
  constructor(scene, city, interiors, hq, corridor, streamer) {
    this.scene = scene
    this.city = city
    this.interiors = interiors
    this.hq = hq
    this.corridor = corridor
    this.streamer = streamer
    this.groundY = city?.meta?.land_level_m ?? 12.0
    this.doors = []
    this.ready = false
    this.active = true       // false while the hero corridor owns the camera
    this.paused = false
    this.stats = { doors: 0, cut: 0, open: 0, state: 'idle' }
    this._saved = this._loadSaved()
    this._lampTarget = 0
    this._audio = null
    this._camera = null
    this._controls = null
    this._ride = null
    this._restored = []

    document.addEventListener('visibilitychange', () => {
      this.paused = document.hidden
    })
  }

  setAudio(audio) { this._audio = audio }

  async load(url = '/doors/doors.json') {
    const data = await fetch(url).then((r) => (r.ok ? r.json() : null))
      .catch(() => null)
    if (!data || !Array.isArray(data.doors)) {
      console.warn('[doors] no doors.json; doorways disabled')
      return this
    }
    // The expansion set (68_build_doors.py --expansion, 631 subway-tranche
    // buildings) is generated with runtimeEnabled: false and lives in its own
    // file. If it is ever pointed at this loader by mistake, refuse it: those
    // entries have no interior room, and cutting a hole into a solid building
    // is worse than no doorway. The gate is a room behind the opening, not a
    // flag.
    if (data.runtimeEnabled === false) {
      console.warn('[doors]', url, 'is marked runtimeEnabled: false',
        `(${data.doors.length} entries); doorways disabled`)
      return this
    }
    for (const cfg of data.doors) this._add(cfg)
    for (const d of this.doors) {
      // the interior answers no keypress once its doorway is real
      d.room.doorway = true
      // the wall cut may rotate the room to a clear frontage, so the
      // assembly is built after it, from the final matrix
      if (d.kind === 'wall') this._cutWall(d)
      this._buildAssembly(d)
      this._cutRoomGlass(d)
    }
    this.ready = this.doors.length > 0
    this.stats.doors = this.doors.length
    // tiles can arrive after boot; re-cut a door's wall when its tile loads
    this.streamer.onReady.push(() => {
      for (const d of this.doors) {
        if (!d.cut && d.kind === 'wall') this._findAndCut(d)
      }
    })
    console.info('[doors]', this.doors.length, 'doorways configured:',
      this.doors.map((d) => `${d.key} (bid ${d.bid})`).join(', '))
    if (this._restored.length) {
      // timing-free evidence for the headless runner's reload check
      window.__doorsBootState = this._restored
    }
    return this
  }

  bind(camera, controls) {
    this._camera = camera
    this._controls = controls
  }

  _add(cfg) {
    // An entrance with no interior behind it stays a closed door. That is the
    // documented behaviour of the `entrance` kind and the reason the ~660
    // expansion set is data-only: the runtime resolves an interior when one
    // exists and cuts nothing when one does not.
    const room = cfg.room
      ? this.interiors.rooms.find((r) => r.key === cfg.room) : null
    if (!room) {
      console.warn('[doors] no interior for', cfg.key,
        cfg.room ?? '(none configured)', '- no opening cut')
      return
    }
    const bayCenter = cfg.bayCenter != null ? cfg.bayCenter : BAY_Y
    const rec = {
      key: cfg.key,
      bid: cfg.bid,
      kind: cfg.kind || 'wall',
      room,
      bayCenter,
      bayY0: bayCenter - GLASS_W / 2,
      bayY1: bayCenter + GLASS_W / 2,
      wallDist: cfg.kind === 'recess'
        ? (cfg.wallDist != null ? cfg.wallDist : RECESS_WALL_DIST) : null,
      state: 'closed',
      progress: 0,
      dwell: 0,
      trigger: false,
      inside: false,
      near: false,
      cut: false,
      mesh: null,
      leaf: null,
      group: null,
      soundAt: 0,
      prevLocalX: null,
    }
    if (this._saved && this._saved.doors && this._saved.doors[cfg.key]) {
      rec.state = 'open'
      rec.progress = 1
      rec.dwell = DWELL_S
      this._restored.push({ key: cfg.key, state: rec.state })
    }
    this.doors.push(rec)
  }

  // ---- wall discovery -----------------------------------------------------

  _buildingVerts(mesh, bid) {
    const attr = mesh.geometry.attributes._bid || mesh.geometry.attributes._BID
    if (!attr) return null
    const set = new Set()
    for (let i = 0; i < attr.count; i++) {
      if (Math.round(attr.getX(i)) === bid) set.add(i)
    }
    if (!set.size) return null
    set.bid = bid
    return set
  }

  _meshBox(mesh) {
    const g = mesh.geometry
    if (!g.boundingSphere) g.computeBoundingSphere()
    if (!g.boundingBox) g.computeBoundingBox()
    return g.boundingBox
  }

  _findMesh(bid, wx, wz) {
    for (const group of this.streamer.pickables()) {
      let found = null
      group.traverse((o) => {
        if (found || !o.isMesh) return
        const g = o.geometry
        if (!(g.attributes._bid || g.attributes._BID)) return
        const bb = this._meshBox(o)
        if (wx < bb.min.x - 2 || wx > bb.max.x + 2 ||
            wz < bb.min.z - 2 || wz > bb.max.z + 2) return
        const s = g.boundingSphere
        if (Math.hypot(wx - s.center.x, wz - s.center.z) > s.radius + 2) return
        if (this._buildingVerts(o, bid)) found = o
      })
      if (found) return found
    }
    return null
  }

  // The street-facing wall of the building nearest the room's doorway, in
  // world space: { frame, wallDist } where the frame's origin is the door
  // axis projected onto the wall plane at ground level. Candidate walls are
  // tried nearest-first, and a wall whose approach is concealed by another
  // building (adjacent footprints overlap in the OSM data) is rejected --
  // a doorway that opens onto a neighbour's wall is not a doorway. Null when
  // no wall face answers.
  _findWall(d, mesh) {
    const pos = mesh.geometry.attributes.position
    const idx = mesh.geometry.index
    const set = this._buildingVerts(mesh, d.bid)
    if (!set) return null
    const doorAxis = this.roomToWorld(d, 0, d.bayCenter, 0)
    doorAxis.y = this.groundY

    const p0 = [0, 0, 0]; const p1 = [0, 0, 0]; const p2 = [0, 0, 0]
    const candidates = []
    const tris = idx ? idx.count / 3 : pos.count / 3
    for (let t = 0; t < tris; t++) {
      const a = idx ? idx.getX(t * 3) : t * 3
      const b = idx ? idx.getX(t * 3 + 1) : t * 3 + 1
      const c = idx ? idx.getX(t * 3 + 2) : t * 3 + 2
      if (!set.has(a) || !set.has(b) || !set.has(c)) continue
      p0[0] = pos.getX(a); p0[1] = pos.getY(a); p0[2] = pos.getZ(a)
      p1[0] = pos.getX(b); p1[1] = pos.getY(b); p1[2] = pos.getZ(b)
      p2[0] = pos.getX(c); p2[1] = pos.getY(c); p2[2] = pos.getZ(c)
      if (Math.max(p0[1], p1[1], p2[1]) < this.groundY - 0.5 ||
          Math.min(p0[1], p1[1], p2[1]) > this.groundY + WALL_H + 0.5) {
        continue
      }
      const n = triNormal3(p0, p1, p2)
      if (n[1] > 0.5 || n[1] < -0.5) continue   // walls only, not roofs/floors
      const cx = (p0[0] + p1[0] + p2[0]) / 3
      const cz = (p0[2] + p1[2] + p2[2]) / 3
      const d2 = (cx - doorAxis.x) ** 2 + (cz - doorAxis.z) ** 2
      // every ground-band wall is a candidate, not just the ones facing the
      // room's current frontage: when that frontage is concealed by an
      // adjacent footprint the room rotates to the next clear wall instead
      candidates.push({ n, p: [cx, p0[1], cz], d2 })
    }
    candidates.sort((a, b) => a.d2 - b.d2)
    for (const cand of candidates) {
      const frame = wallFrame(cand.n)
      const ax = doorAxis.x - cand.p[0]
      const ay = doorAxis.y - cand.p[1]
      const az = doorAxis.z - cand.p[2]
      const t = -(ax * cand.n[0] + ay * cand.n[1] + az * cand.n[2])
      const proj = [
        cand.p[0] + cand.n[0] * t,
        cand.p[1] + cand.n[1] * t,
        cand.p[2] + cand.n[2] * t,
      ]
      frame.o = [proj[0], this.groundY, proj[2]]
      if (!this._approachClear(d, frame)) continue
      const wallDist = Math.abs(
        (cand.p[0] - d.room.group.position.x) * cand.n[0] +
        (cand.p[1] - d.room.group.position.y) * cand.n[1] +
        (cand.p[2] - d.room.group.position.z) * cand.n[2])
      return { frame, wallDist }
    }
    return null
  }

  // Is the approach to a wall frame clear for APPROACH_R metres? A ray from
  // just outside the wall toward the street must not meet another building's
  // wall -- adjacent footprints overlap in the OSM data, and a doorway that
  // opens onto a neighbour is worse than no doorway. Buildings share merged
  // tile meshes, so the test is by building id, never by object identity:
  // the same mesh holds both the target building and the neighbour.
  _approachClear(d, frame) {
    const raycaster = new THREE.Raycaster()
    const ox = frame.o[0] + frame.normal[0] * 0.4
    const oz = frame.o[2] + frame.normal[2] * 0.4
    raycaster.set(
      new THREE.Vector3(ox, this.groundY + 1.5, oz),
      new THREE.Vector3(frame.normal[0], 0, frame.normal[2]))
    raycaster.far = APPROACH_R
    const seen = []
    for (const group of this.streamer.pickables()) {
      const hits = raycaster.intersectObjects(group, true)
      for (const h of hits) {
        const attr = h.object.geometry.attributes._bid ||
          h.object.geometry.attributes._BID
        if (!attr) continue
        const bid = Math.round(attr.getX(h.face ? h.face.a : 0))
        seen.push({ bid, d: +h.distance.toFixed(2),
          obj: h.object.name || h.object.type })
        if (bid !== d.bid) {
          d.lastClear = { ok: false, seen,
            origin: [+ox.toFixed(1), 1.5, +oz.toFixed(1)] }
          return false
        }
      }
    }
    d.lastClear = { ok: true, seen,
      origin: [+ox.toFixed(1), 1.5, +oz.toFixed(1)] }
    return true
  }

  _cutWall(d) {
    const b = d.room.building
    const wx = b ? b.x : this.city.x(d.bid)
    const wz = b ? -b.y : -this.city.y(d.bid)
    const mesh = this._findMesh(d.bid, wx, wz)
    if (!mesh) return false
    let wall = this._findWall(d, mesh)
    if (!wall) return false

    if (!d.relocated) {
      // A blocked default frontage (adjacent footprint overlap) means the
      // doorway has to face the clear wall instead: rotate the room so its
      // glazed wall looks out through the chosen opening, then rebase every
      // camera position the corridor and the HUD derive from the room.
      const n = wall.frame.normal
      const yaw = Math.atan2(n[2], -n[0])
      d.room.group.rotation.y = yaw
      d.room.group.updateMatrixWorld(true)
      d.room.yaw = yaw
      this.interiors.rebase(d.room)
      d.relocated = true
      // the assembly is built from the room's matrix; a relocation that
      // happens after load (tile arrived late) must rebuild it
      if (d.group) this._buildAssembly(d)
      // re-resolve the wall from the rotated room, so the door axis lands on
      // the new frontage exactly
      wall = this._findWall(d, mesh) || wall
    }
    d.wallDist = wall.wallDist

    // move the room so its glazed entrance wall sits just inside the cut, or
    // the walk-in would land the player inside the solid building mass
    if (!d.shifted) {
      const doorDir = this._doorDir(d)
      d.room.group.position.addScaledVector(doorDir, wall.wallDist - WALL_GAP)
      d.room.group.updateMatrixWorld(true)
      d.shifted = true
    }

    // the frame origin is on the door axis, so the cut rect is centred on it
    const rect = { u0: -WALL_W / 2, u1: WALL_W / 2, v0: 0, v1: WALL_H }
    const r = cutWallInMesh(mesh.geometry, this._buildingVerts(mesh, d.bid),
      wall.frame, rect)
    if (r.geometry !== mesh.geometry) {
      d.mesh = mesh
      mesh.geometry = r.geometry
      this.stats.cut += r.cut
    }
    d.cut = r.cut > 0 || r.removed > 0
    d.cutFaces = r.cut
    d.removedTris = r.removed

    // A passage cut: some footprints in the OSM data overlap their
    // neighbours by a metre or more (the corridor market's block shares its
    // outline with an adjacent school), so the doorway volume may contain
    // another building's wall just inside the target's own.
    //
    // This used to be a blunt AABB-overlap sweep over every tile mesh
    // touching the door volume, dropping any triangle whose box crossed. That
    // is far too coarse in a merged tile mesh: a neighbour's wall quad runs
    // ground to roof, so the whole facade went — and worse, the four exact
    // pieces the cut above had just left around the hole have AABBs touching
    // the box too, so the careful cut was immediately blown out. The doorway
    // must be a doorway, not a demolition.
    //
    // So: the same exact rect subtraction, in the same wall frame, applied to
    // the *other* buildings' faces only (the target's wall is already cut),
    // plus a containment sweep for the faces that are not parallel to the
    // wall and so cannot be rect-subtracted. Both are counted.
    const box = this._doorBox(wall.frame)
    d.passageRemoved = 0
    d.passageCutFaces = 0
    d.passageBoxRemoved = 0
    for (const group of this.streamer.pickables()) {
      group.traverse((o) => {
        if (!o.isMesh) return
        const g = o.geometry
        if (!(g.attributes._bid || g.attributes._BID)) return
        if (!g.boundingSphere) g.computeBoundingSphere()
        const s = g.boundingSphere
        if (s.center.x < box.min[0] - s.radius ||
            s.center.x > box.max[0] + s.radius ||
            s.center.y < box.min[1] - s.radius ||
            s.center.y > box.max[1] + s.radius ||
            s.center.z < box.min[2] - s.radius ||
            s.center.z > box.max[2] + s.radius) return
        let geom = g
        let touched = false
        const others = this._verticesExcept(o, d.bid)
        if (others) {
          const rc = cutWallInMesh(geom, others, wall.frame, rect)
          if (rc.geometry !== geom) {
            geom = rc.geometry
            touched = true
            d.passageCutFaces += rc.cut
          }
        }
        const rb = cutContained(geom, box, (bid) => bid !== d.bid)
        if (rb.geometry !== geom) {
          geom = rb.geometry
          touched = true
          d.passageBoxRemoved += rb.removed
        }
        if (touched) {
          o.geometry = geom
          d.passageRemoved++
        }
      })
    }
    return d.cut
  }

  // Every vertex index in a merged tile mesh that does *not* belong to `bid`.
  // The returned set carries .bid = null so a re-emitted face keeps its own
  // building id rather than being relabelled as the target's.
  _verticesExcept(mesh, bid) {
    const attr = mesh.geometry.attributes._bid || mesh.geometry.attributes._BID
    if (!attr) return null
    const set = new Set()
    for (let i = 0; i < attr.count; i++) {
      if (Math.round(attr.getX(i)) !== bid) set.add(i)
    }
    if (!set.size) return null
    set.bid = null
    return set
  }

  // The doorway volume in world space, as an axis-aligned box: WALL_W plus a
  // jamb margin along the wall, the full door height, and 1.5 m of wall
  // thickness either side of the wall plane.
  _doorBox(frame) {
    const corners = []
    for (const u of [-WALL_W / 2 - 0.2, WALL_W / 2 + 0.2]) {
      for (const v of [-0.1, WALL_H + 0.1]) {
        for (const w of [-1.5, 1.5]) {
          const p = framePoint(frame, u, v)
          corners.push([
            p[0] + frame.normal[0] * w,
            p[1] + frame.normal[1] * w,
            p[2] + frame.normal[2] * w,
          ])
        }
      }
    }
    const min = [Infinity, Infinity, Infinity]
    const max = [-Infinity, -Infinity, -Infinity]
    for (const c of corners) {
      for (let i = 0; i < 3; i++) {
        if (c[i] < min[i]) min[i] = c[i]
        if (c[i] > max[i]) max[i] = c[i]
      }
    }
    return { min, max }
  }

  // A wall door's cut lives in a tile mesh; a tile that streams out and back
  // in brings fresh uncut geometry, so the cut has to be re-applied.
  _meshLive(d) {
    return !!(d.mesh && d.mesh.parent && d.mesh.parent.parent)
  }

  _findAndCut(d) {
    if (d.kind !== 'wall') return
    if (d.cut && this._meshLive(d)) return
    this._cutWall(d)
  }

  // Punch the door opening in the room's glazed wall. Each room instance has
  // its own cloned geometry (interiors.place clones), so one cut cannot leak
  // into another room that reuses the same authored mesh.
  //
  // The rect is expressed in the glaze mesh's own local axes, which are the
  // group's, not the authored ones: u = mesh z = along the wall (authored +y
  // to the left is mesh -z), v = mesh y = up.
  _cutRoomGlass(d) {
    const rect = {
      u0: -d.bayY1, u1: -d.bayY0,
      v0: GLASS_SILL, v1: GLASS_SILL + GLASS_H,
    }
    d.glazeCut = 0
    d.glazeRemoved = 0
    d.glazeKept = 0
    for (const child of d.room.group.children) {
      if (!child.isMesh || !child.userData.glaze) continue
      const r = cutGlazeRect(child.geometry, rect)
      if (r.geometry !== child.geometry) child.geometry = r.geometry
      d.glazeCut += r.cut
      d.glazeRemoved += r.removed
      d.glazeKept += r.kept
    }
  }

  // ---- door assembly ------------------------------------------------------

  _wallPlaneX(d) {
    return d.kind === 'recess' ? -(d.wallDist - 0.1) : -WALL_GAP
  }

  _buildAssembly(d) {
    const room = d.room
    // a late relocation (tile arrived after boot) must rebuild the assembly
    // at the room's final matrix
    if (d.group) {
      this.scene.remove(d.group)
      d.group.traverse((o) => {
        if (o.isMesh) {
          o.geometry.dispose()
          if (Array.isArray(o.material)) o.material.forEach((m) => m.dispose())
          else o.material.dispose()
        }
      })
      d.group = null
      d.leaf = null
    }
    const group = new THREE.Group()
    group.name = `DOOR_${d.key}`
    group.position.copy(room.group.position)
    group.rotation.copy(room.group.rotation)
    this.scene.add(group)
    d.group = group

    // Everything below is authored-frame (+x into, +y left, +z up). This one
    // rotation is the (x, y, z) -> (x, z, -y) swap in matrix form, applied
    // exactly once, so the boxes read the way the room was authored. Without
    // it the assembly came out rotated 90 deg about x: the sliding leaf
    // measured 1.76 m tall instead of 2.36, and the lit ceiling panel sat at
    // 0.17-1.83 m above the pavement instead of 2.66 m.
    const authored = new THREE.Group()
    authored.name = 'authored'
    authored.rotation.x = AUTHORED_ROT_X
    group.add(authored)

    const y0 = d.bayY0
    const y1 = d.bayY1
    const mat = this.interiors.material
    const glass = this.interiors.glassMaterial
    const xWall = this._wallPlaneX(d)

    // ---- frame ------------------------------------------------------------
    const frameG = new THREE.Group()
    frameG.name = 'frame'
    frameG.add(
      boxMesh(xWall, y0 - 0.05, 1.25, 0.18, 0.14, 2.44, METAL, mat),
      boxMesh(xWall, y1 + 0.05, 1.25, 0.18, 0.14, 2.44, METAL, mat),
      boxMesh(xWall, (y0 + y1) / 2, 2.5, 0.18, y1 - y0 + 0.28, 0.16, METAL, mat),
      boxMesh(xWall, (y0 + y1) / 2, SILL / 2, 0.3, y1 - y0 + 0.28, SILL,
        WALL_DARK, mat),
      boxMesh(xWall + LEAF_Z, (y0 + y1) / 2, TRACK_Z + 0.06, 0.1,
        y1 - y0 + 0.4, 0.06, WALL_DARK, mat),
    )
    authored.add(frameG)

    // ---- automatic sliding leaf -------------------------------------------
    // A panel in the wall plane that slides +y: closed it covers the opening,
    // open it parks against the wall beside it — the honest version of an
    // automatic door where no pocket exists in a cut opening. Thin in the
    // room's x (the wall plane), long along y (the slide axis), tall in z.
    const leafG = new THREE.Group()
    leafG.name = 'leaf'
    leafG.add(
      boxMesh(0, LEAF_W / 2, SILL + LEAF_H / 2, 0.08, LEAF_W, LEAF_H,
        METAL, mat),
      boxMesh(0, LEAF_W / 2, SILL + LEAF_H / 2, 0.05, LEAF_W - 0.16,
        LEAF_H - 0.16, GLASS, glass),
      boxMesh(0, LEAF_W - 0.05, SILL + LEAF_H * 0.55, 0.03, 0.06, 0.9,
        METAL, mat),
    )
    leafG.position.set(xWall + LEAF_Z, y0 + 0.02, 0)
    d.leaf = leafG
    authored.add(leafG)

    // ---- lit ceiling panel over the threshold ------------------------------
    authored.add(boxMesh(xWall - 0.1, (y0 + y1) / 2, TRACK_Z + 0.16, 0.5,
      y1 - y0 - 0.1, 0.05, PANEL_LIT, mat))

    group.updateMatrixWorld(true)
  }

  // ---- trigger, crossing, preload -----------------------------------------

  // A world point in the room's *authored* frame: x into the room, y left
  // along the entrance wall, z up from the room floor. Every trigger,
  // crossing, preload and probe below reads these, so the swap happens here
  // and only here.
  _local(d, p, out) {
    return localToAuth(d.room.group.worldToLocal(out.copy(p)), out)
  }

  // The inverse: an authored-frame point of this room, in world space. Public
  // because the headless runner (scripts/qa/doorcheck-run.mjs) places its
  // cameras in the same frame and must not re-derive the swap.
  roomToWorld(d, x, y, z, out = new THREE.Vector3()) {
    return d.room.group.localToWorld(authToLocal(x, y, z, out))
  }

  // World direction of authored +x — into the room, through the doorway.
  // (authored +x is group-local +x, so this one needs no swap; it is here so
  // the two call sites cannot drift apart.)
  _doorDir(d, out = new THREE.Vector3()) {
    return d.room.group.localToWorld(out.set(1, 0, 0))
      .sub(d.room.group.position).normalize()
  }

  _inTrigger(d, camera) {
    const v = this._local(d, camera.position, new THREE.Vector3())
    const xWall = this._wallPlaneX(d)
    return v.x > xWall + TRIGGER_X[0] && v.x < xWall + TRIGGER_X[1] &&
      v.y > d.bayY0 - TRIGGER_MARGIN_Y && v.y < d.bayY1 + TRIGGER_MARGIN_Y &&
      v.z > TRIGGER_Z[0] && v.z < TRIGGER_Z[1]
  }

  _inOpening(d, camera) {
    const v = this._local(d, camera.position, new THREE.Vector3())
    const xWall = this._wallPlaneX(d)
    return Math.abs(v.x - xWall) < 1.0 &&
      v.y > d.bayY0 - 0.4 && v.y < d.bayY1 + 0.4 &&
      v.z > 0 && v.z < 3.0
  }

  _leafBox(d, outMin, outMax) {
    if (!d.leaf) return null
    d.leaf.updateMatrixWorld(true)
    const b = new THREE.Box3().setFromObject(d.leaf)
    outMin.set(b.min.x - OBSTRUCT_MARGIN, b.min.y - OBSTRUCT_MARGIN,
      b.min.z - OBSTRUCT_MARGIN)
    outMax.set(b.max.x + OBSTRUCT_MARGIN, b.max.y + OBSTRUCT_MARGIN,
      b.max.z + OBSTRUCT_MARGIN)
    return [outMin, outMax]
  }

  _obstructed(d, camera) {
    if (this._inOpening(d, camera)) return true
    const m = this._leafBox(d, new THREE.Vector3(), new THREE.Vector3())
    if (!m) return false
    const p = camera.position
    return p.x > m[0].x && p.x < m[1].x && p.y > m[0].y && p.y < m[1].y &&
      p.z > m[0].z && p.z < m[1].z
  }

  // Physical enter/exit at the wall plane: the camera is never moved; the
  // room state, collider set and lamp follow the crossing instead. Entering
  // means stepping from the street side (x < plane) through the plane into
  // the building; exiting is the reverse. The comparisons are inclusive so a
  // camera stepping 0.14 m per frame cannot skip the edge by landing exactly
  // on it, and the deadband on both sides stops a camera idling on the plane
  // from flipping the state every frame.
  _crossing(d, camera) {
    if (!this.active || this.paused || this.corridor?.active) return
    const v = this._local(d, camera.position, new THREE.Vector3())
    const plane = this._wallPlaneX(d)
    const prev = d.prevLocalX
    d.prevLocalX = v.x
    if (prev == null) return
    if (Math.abs(v.y - d.bayCenter) > 1.3 || v.z < 0 || v.z > 3.0) return
    const m = ENTER_MARGIN
    const inside = this.interiors.inside === d.room
    if (!inside && prev < plane - m && v.x >= plane - m) {
      this.interiors.enterPhysical(d.room)
      d.inside = true
    } else if (inside && prev > plane + m && v.x <= plane + m) {
      this.interiors.exitPhysical()
      d.inside = false
    }
  }

  // Interior zone preloading: the room and its lamp come up while the player
  // is still outside the threshold, so the opening never frames a black void.
  // Distances are measured from the wall plane, not the room origin — the HQ
  // threshold sits 4.9 m in front of its room.
  _preload(camera) {
    if (this.corridor?.active || this.paused) return
    if (this.interiors.inside) {
      this._lampTarget = this.interiors.inside.lamp ?? 1.9
      return
    }
    let nearest = null
    let nd = Infinity
    for (const d of this.doors) {
      if (!d.group) continue
      const c = this._local(d, camera.position, new THREE.Vector3())
      const dist = Math.hypot(c.x - this._wallPlaneX(d), c.y - d.bayCenter)
      if (dist < nd) { nd = dist; nearest = d }
    }
    let target = 0
    if (nearest && nd < PRELOAD_R) {
      nearest.room.group.visible = true
      target = 0.55
    }
    for (const d of this.doors) {
      if (this.interiors.inside === d.room || !d.room.group.visible) continue
      const c = this._local(d, camera.position, new THREE.Vector3())
      if (Math.hypot(c.x - this._wallPlaneX(d), c.y - d.bayCenter) >
          PRELOAD_R + 3) {
        d.room.group.visible = false
      }
    }
    this._lampTarget = target
  }

  _rampLamp(dt) {
    const lamp = this.interiors.lamp
    const cur = lamp.intensity
    const target = this._lampTarget
    if (Math.abs(cur - target) < 0.01) return
    const step = 1.4 * dt
    lamp.intensity = cur < target
      ? Math.min(target, cur + step)
      : Math.max(target, cur - step)
  }

  // ---- the state machine --------------------------------------------------

  _setState(d, state) {
    if (d.state === state) return
    d.state = state
    d.dwell = 0
    this._save()
    if (state === 'opening' || state === 'closing') this._swish(d)
  }

  _swish(d) {
    if (!this._audio) return
    const now = performance.now()
    if (now - d.soundAt > 500) {
      d.soundAt = now
      this._audio.doorSwish()
    }
  }

  _save() {
    const state = {}
    for (const d of this.doors) {
      if (d.state !== 'closed') state[d.key] = d.state
    }
    try {
      localStorage.setItem(SAVE_KEY, JSON.stringify({
        v: 1, doors: state, at: Date.now(),
      }))
    } catch { /* storage unavailable: door state simply does not persist */ }
  }

  _loadSaved() {
    try {
      const raw = localStorage.getItem(SAVE_KEY)
      return raw ? JSON.parse(raw) : null
    } catch { return null }
  }

  update(dt, camera) {
    if (!this.ready) return this.stats
    if (this.corridor?.active) {
      this.stats.state = 'corridor'
      return this.stats
    }
    if (this.paused) {
      this.stats.state = 'paused'
      return this.stats
    }
    if (this._ride) {
      this._rideStep(dt)
      this.stats.state = 'lift'
      return this.stats
    }
    this._preload(camera)
    this._rampLamp(dt)

    let open = 0
    for (const d of this.doors) {
      if (!d.group) continue
      if (d.kind === 'wall' && (!d.cut || !this._meshLive(d))) {
        const c = this._local(d, camera.position, new THREE.Vector3())
        if (c.length() < CUT_R) this._findAndCut(d)
      }
      const c = this._local(d, camera.position, new THREE.Vector3())
      d.near = Math.hypot(c.x - this._wallPlaneX(d), c.y - d.bayCenter) < 14

      const inTrigger = this._inTrigger(d, camera)
      d.trigger = inTrigger
      this._crossing(d, camera)

      switch (d.state) {
        case 'closed':
          if (inTrigger) this._setState(d, 'opening')
          break
        case 'opening':
          d.progress = Math.min(1, d.progress + dt / OPEN_S)
          if (d.progress >= 1) this._setState(d, 'open')
          break
        case 'open':
          d.dwell += dt
          if (!inTrigger && d.dwell > DWELL_S) this._setState(d, 'closing')
          break
        case 'closing':
          if (inTrigger || this._obstructed(d, camera)) {
            this._setState(d, 'opening')     // never close on the player
            break
          }
          d.progress = Math.max(0, d.progress - dt / CLOSE_S)
          if (d.progress <= 0) this._setState(d, 'closed')
          break
      }
      if (d.state === 'open') open++
      if (d.leaf) {
        d.leaf.position.y = d.bayY0 + 0.02 + d.progress * LEAF_W
      }
    }
    this.stats.open = open
    this.stats.state = open ? 'open' : 'closed'
    return this.stats
  }

  // Meshes the walk collider should test near this door.
  pickables() {
    const out = []
    for (const d of this.doors) {
      if (d.group && (d.near || this.interiors.inside === d.room)) {
        out.push(d.group)
      }
    }
    return out
  }

  // How far the camera is into a threshold (0..1) — feeds the audio mix.
  indoorBlend(camera) {
    let best = 0
    for (const d of this.doors) {
      if (!d.group) continue
      const c = this._local(d, camera.position, new THREE.Vector3())
      const plane = this._wallPlaneX(d)
      const dx = Math.abs(c.x - plane)
      if (dx < 1.2 && Math.abs(c.y - d.bayCenter) < 1.5 && c.z > 0 && c.z < 3) {
        best = Math.max(best, 1 - dx / 1.2)
      }
    }
    return best
  }

  // ---- physical lift rides -------------------------------------------------

  // E at a lift link becomes a ride in the corridor's own cab: the camera
  // travels the shaft and the arrival is placed at the room's authored shot,
  // not a jump from one building to another.
  rideLift(link, camera, controls) {
    if (this.corridor?.active || this.paused || this._ride) return false
    const from = this.interiors.inside
    const to = link && link.room
    const cab = this.corridor && this.corridor.lift
    if (!from || !to || !cab) return false
    this._ride = {
      cab, camera, controls, from, to,
      t: 0,
      dur: 1.4 + Math.abs(from.local(2, 0, 0).y - to.local(2, 0, 0).y) / 26.0,
      y0: from.local(2, 0, 0).y,
      y1: to.local(2, 0, 0).y,
      yaw: from.yaw,
    }
    const p = from.local(2, 0, 0)
    cab.position.set(p.x, p.y, p.z)
    cab.rotation.set(0, from.yaw, 0)
    cab.visible = true
    cab.updateMatrixWorld(true)
    this.interiors.lamp.intensity = 1.6
    this._rideLook(camera, controls, cab)
    return true
  }

  _rideLook(camera, controls, cab) {
    cab.updateMatrixWorld(true)
    camera.position.copy(
      cab.localToWorld(new THREE.Vector3(1.15, 1.7, 0)))
    camera.lookAt(cab.localToWorld(new THREE.Vector3(-3.0, 1.45, 0)))
    const e = new THREE.Euler().setFromQuaternion(camera.quaternion, 'YXZ')
    if (controls) { controls.yaw = e.y; controls.pitch = e.x }
  }

  _rideStep(dt) {
    const r = this._ride
    if (!r) return
    r.t += dt
    const u = Math.min(1, r.t / r.dur)
    const s = u * u * (3 - 2 * u)
    r.cab.position.y = r.y0 + (r.y1 - r.y0) * s
    r.cab.updateMatrixWorld(true)
    this._rideLook(r.camera, r.controls, r.cab)
    if (u >= 1) {
      const to = r.to
      r.cab.visible = false
      this.interiors.enterPhysical(to)
      this._ride = null
      if (to.shot) {
        r.camera.position.copy(to.shot.eye)
        r.camera.lookAt(to.shot.at)
        const e = new THREE.Euler().setFromQuaternion(
          r.camera.quaternion, 'YXZ')
        if (r.controls) { r.controls.yaw = e.y; r.controls.pitch = e.x }
      }
    }
  }

  // ---- verification --------------------------------------------------------
  // Measured, per HANDOFF §0. Each check returns numbers; the headless runner
  // applies the thresholds (scripts/qa/doorcheck-run.mjs).

  verify() {
    const out = { ok: true, checks: [] }
    const say = (name, ok, d) => {
      out.checks.push({ name, ok, ...d })
      if (!ok) out.ok = false
    }

    for (const d of this.doors) {
      if (!d.group) {
        say(`${d.key} placed`, false, { reason: 'no assembly group' })
        continue
      }
      // The glaze counts are the "no missing wall" evidence: a doorway leaves
      // glass standing either side of the opening (glazeKept > 0), it does
      // not delete the pane.
      say(`${d.key} placed`, true, {
        state: d.state, kind: d.kind, bid: d.bid,
        wallDist_m: +(d.wallDist ?? -1).toFixed(2),
        relocated: !!d.relocated, shifted: !!d.shifted,
        cutFaces: d.cutFaces, removedTris: d.removedTris,
        passageRemoved: d.passageRemoved,
        passageCutFaces: d.passageCutFaces,
        passageBoxRemoved: d.passageBoxRemoved,
        glazeCutFaces: d.glazeCut, glazeRemovedTris: d.glazeRemoved,
        glazeTrisKept: d.glazeKept,
        assembly: this._assemblyMetrics(d),
        lastClear: d.lastClear,
      })

      const res = this._probeOpening(d)
      say(`${d.key} opening is real (render)`, res.blocked === 0, {
        rays: res.rays, blocked: res.blocked,
        wallCut: d.kind === 'wall' ? d.cut : 'authored recess',
        wallDist_m: +(d.wallDist ?? -1).toFixed(2),
      })

      const walk = this._walkTest(d, 1)
      say(`${d.key} walk-in crosses without teleport`,
        walk.crossed && walk.maxJump < 0.5 && walk.inside,
        { maxJump_m: +walk.maxJump.toFixed(3), frames: walk.frames,
          inside: walk.inside, doorState: walk.doorState,
          maxJumpAt: walk.maxJumpAt })

      const rev = this._walkTest(d, -1)
      say(`${d.key} reverse traversal exits`,
        rev.crossed && !rev.inside,
        { maxJump_m: +rev.maxJump.toFixed(3), frames: rev.frames,
          inside: rev.inside, maxJumpAt: rev.maxJumpAt })

      const cyc = this._cycleTest(d)
      say(`${d.key} door cycle opens and closes`, cyc.openCycles >= 2 &&
        cyc.closedOnce, cyc)

      const obs = this._obstructionTest(d)
      say(`${d.key} obstruction reopens`, obs.reopened, obs)

      const pre = this._preloadTest(d)
      say(`${d.key} interior preloads`, pre.visible && pre.lamp > 0.2, pre)
    }

    const pause = this._pauseTest()
    say('pause freezes the door machine', pause.frozen, pause)

    return out
  }

  // Is the assembly standing up the way it was authored? The frame convention
  // error this file shipped with was invisible to every behavioural check —
  // the door still cycled, the trigger still fired — but it laid the assembly
  // on its side. These three numbers catch it without a render: a door leaf
  // is taller than it is wide, and the lit panel is overhead.
  _assemblyMetrics(d) {
    if (!d.leaf || !d.group) return null
    d.group.updateMatrixWorld(true)
    const leaf = new THREE.Box3().setFromObject(d.leaf)
    const panel = d.group.getObjectByName('authored')
    const lit = panel ? panel.children[panel.children.length - 1] : null
    const litBox = lit ? new THREE.Box3().setFromObject(lit) : null
    const floor = this.roomToWorld(d, 0, d.bayCenter, 0).y
    return {
      leafHeight_m: +(leaf.max.y - leaf.min.y).toFixed(2),
      leafWidth_m: +Math.max(leaf.max.x - leaf.min.x,
        leaf.max.z - leaf.min.z).toFixed(2),
      litPanelAboveFloor_m: litBox
        ? +(litBox.min.y - floor).toFixed(2) : null,
    }
  }

  // Rays through the door rect from the street side at eye height, against
  // the city meshes plus the HQ tower. Any hit before the room (wall band
  // region) means the opening is not actually there. The hits' object names
  // and building ids are recorded so a blocked ray says *what* blocked it.
  _probeOpening(d) {
    const raycaster = new THREE.Raycaster()
    let blocked = 0
    const dir = this._doorDir(d)
    const plane = this._wallPlaneX(d)
    const cols = 5
    const rows = 3
    const rays = []
    const colliders = [...this.streamer.pickables()]
    if (this.hq && this.hq.tower) colliders.push(this.hq.tower.children[0])
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        const y = d.bayY0 + (c + 0.5) / cols * (d.bayY1 - d.bayY0)
        const z = 1.2 + r / rows * 1.1
        const origin = this.roomToWorld(d, plane - 2.0, y, z)
        raycaster.set(origin, dir)
        raycaster.far = 4.5
        const hit = raycaster.intersectObjects(colliders, true)[0]
        const blockedHere = !!hit && hit.distance < 3.8
        if (blockedHere) blocked++
        rays.push({
          hit: blockedHere,
          distance: hit ? +hit.distance.toFixed(2) : null,
          object: hit && hit.object ? hit.object.name || hit.object.type : null,
          bid: hit && hit.object && hit.object.geometry &&
            (hit.object.geometry.attributes._bid ||
             hit.object.geometry.attributes._BID)
            ? Math.round((hit.object.geometry.attributes._bid ||
                hit.object.geometry.attributes._BID).getX(
                  hit.face ? hit.face.a : 0)) : null,
        })
      }
    }
    return { rays: rays.length, blocked, rays }
  }

  // Drive the camera straight through the doorway with the real walk
  // controls (keys + controls.update), recording position continuity.
  // dir +1 = street to room, -1 = room to street. The collider set is
  // refreshed every step so the door assembly joins it as the player closes
  // in (the render loop is frozen by the QA runner during these tests).
  // opts.trace collects the sampled camera positions, so the runner can
  // prove determinism by replaying the identical walk twice.
  _walkTest(d, dir, opts = {}) {
    const camera = this._camera
    const controls = this._controls
    if (!camera || !controls) {
      return { crossed: false, maxJump: 1e9, frames: 0, inside: false }
    }
    const colliders = () => {
      const list = [...this.streamer.pickables()]
      for (const g of this.pickables()) list.push(g)
      if (this.hq && this.hq.tower) list.push(this.hq.tower.children[0])
      controls.setColliders(list)
    }
    const plane = this._wallPlaneX(d)
    if (dir < 0) this.interiors.enterPhysical(d.room)
    const start = this.roomToWorld(d, plane - dir * 3.2, d.bayCenter, 1.7)
    const target = this.roomToWorld(d, plane + dir * 3.0, d.bayCenter, 1.7)
    camera.position.copy(start)
    controls.mode = 'walk'
    const dx = target.x - start.x
    const dz = target.z - start.z
    // world forward for yaw is (-sin yaw, 0, -cos yaw); solve for the
    // direction that points at the doorway
    controls.yaw = Math.atan2(-dx, -dz)
    controls.pitch = 0
    camera.quaternion.setFromEuler(new THREE.Euler(0, controls.yaw, 0, 'YXZ'))
    controls.keys.add('KeyW')
    let maxJump = 0
    let maxJumpAt = null
    let prev = camera.position.clone()
    let crossed = false
    let reachedInside = this.interiors.inside === d.room
    const frames = 180
    const dt = 1 / 30
    const lp = new THREE.Vector3()
    const trace = opts.trace ? [] : null
    let prevVX = null
    let i = 0
    const m = ENTER_MARGIN
    for (; i < frames; i++) {
      colliders()
      this.update(dt, camera)
      controls.update(dt)
      // crossing mirrors _crossing's deadband: the camera has to move
      // through the plane band, not merely start on the far side of it
      const v = this._local(d, camera.position, lp)
      if (i >= 5) {
        // skip the first frames: gravity settles the eye onto the ground
        if (prevVX != null) {
          const goingIn = dir > 0 &&
            prevVX < plane - m && v.x >= plane - m
          const goingOut = dir < 0 &&
            prevVX > plane + m && v.x <= plane + m
          if (goingIn || goingOut) crossed = true
        }
        prevVX = v.x
      }
      if (trace && i >= 5) trace.push([+camera.position.x.toFixed(3),
        +camera.position.y.toFixed(3), +camera.position.z.toFixed(3)])
      const jump = camera.position.distanceTo(prev)
      if (i >= 5 && jump > maxJump) {
        maxJump = jump
        let groundHit = null
        const gr = new THREE.Raycaster(
          new THREE.Vector3(camera.position.x, camera.position.y + 1,
            camera.position.z),
          new THREE.Vector3(0, -1, 0), 0, 600)
        const gh = gr.intersectObjects(controls.colliders, true)[0]
        if (gh) {
          const attr = gh.object.geometry.attributes._bid ||
            gh.object.geometry.attributes._BID
          groundHit = {
            y: +gh.point.y.toFixed(2),
            obj: gh.object.name || gh.object.type,
            bid: attr ? Math.round(attr.getX(gh.face ? gh.face.a : 0)) : null,
          }
        }
        // every collider mesh whose AABB crosses the vertical segment below
        // the camera — the definitive list of what could be underfoot
        const under = []
        for (const c of controls.colliders) {
          c.traverse((o) => {
            if (!o.isMesh) return
            const g = o.geometry
            if (!g.boundingBox) g.computeBoundingBox()
            const b = g.boundingBox
            const px = camera.position.x
            const pz = camera.position.z
            if (px > b.min.x && px < b.max.x && pz > b.min.z &&
                pz < b.max.z && b.max.y > 11.9) {
              under.push({
                obj: o.name || o.type,
                y: [+b.min.y.toFixed(1), +b.max.y.toFixed(1)],
              })
            }
          })
        }
        maxJumpAt = {
          frame: i,
          from: [prev.x, prev.y, prev.z].map((v) => +v.toFixed(3)),
          to: [camera.position.x, camera.position.y, camera.position.z]
            .map((v) => +v.toFixed(3)),
          doorState: d.state,
          leafY: d.leaf ? +d.leaf.position.y.toFixed(3) : null,
          groundHit,
          under,
        }
      }
      prev.copy(camera.position)
      reachedInside = this.interiors.inside === d.room
      // the crossing fires at the plane boundary; the walk is complete once
      // the room state has actually flipped (a few frames later)
      const done = crossed && (dir > 0 ? reachedInside : !reachedInside)
      if (done) break
    }
    controls.keys.delete('KeyW')
    this.interiors.exitPhysical()
    for (const r of this.doors) {
      if (r.room.group.visible) r.room.group.visible = false
    }
    this._lampTarget = 0
    this.interiors.lamp.intensity = 0
    return { crossed, maxJump, maxJumpAt, frames: i + 1, inside: reachedInside,
      doorState: d.state, trace }
  }

  _cycleTest(d) {
    const camera = this._camera
    if (!camera) return { openCycles: 0, closedOnce: false, reason: 'no camera' }
    const plane = this._wallPlaneX(d)
    const outside = this.roomToWorld(d, plane - 4, d.bayCenter, 1.7)
    const atDoor = this.roomToWorld(d, plane - 0.6, d.bayCenter, 1.7)
    let openCycles = 0
    let closedOnce = false
    const step = (pos, frames) => {
      camera.position.copy(pos)
      for (let i = 0; i < frames; i++) {
        this.update(1 / 30, camera)
      }
    }
    // arrive, wait for the door to open, leave, wait for it to close -- twice
    step(outside, 5)
    step(atDoor, 90)
    if (d.state === 'open') openCycles = 1
    step(outside, 240)
    if (d.state === 'closed') closedOnce = true
    step(atDoor, 90)
    if (d.state === 'open') openCycles++
    step(outside, 240)
    if (d.state === 'closed') closedOnce = true
    this.interiors.exitPhysical()
    return { openCycles, closedOnce }
  }

  _obstructionTest(d) {
    const camera = this._camera
    if (!camera) return { reopened: false, reason: 'no camera' }
    const plane = this._wallPlaneX(d)
    const at = this.roomToWorld(d, plane - 0.1, d.bayCenter, 1.2)
    camera.position.copy(at)
    d.trigger = false
    this._setState(d, 'closed')
    this._setState(d, 'opening')
    for (let i = 0; i < 40; i++) this.update(1 / 30, camera)
    // the player is still inside the opening: force a close and expect reopen
    d.trigger = false
    this._setState(d, 'closing')
    d.progress = 0.2
    let reopened = false
    for (let i = 0; i < 40; i++) {
      this.update(1 / 30, camera)
      if (d.state === 'opening') { reopened = true; break }
    }
    this.interiors.exitPhysical()
    d.trigger = false
    this._setState(d, 'closed')
    return { reopened, state: d.state }
  }

  _preloadTest(d) {
    const camera = this._camera
    if (!camera) return { visible: false, lamp: 0, reason: 'no camera' }
    const plane = this._wallPlaneX(d)
    const at = this.roomToWorld(d, plane - 7, d.bayCenter, 1.7)
    camera.position.copy(at)
    for (let i = 0; i < 20; i++) this.update(1 / 30, camera)
    const lamp = this.interiors.lamp.intensity
    const visible = d.room.group.visible
    this.interiors.exitPhysical()
    for (const r of this.doors) {
      if (r.room.group.visible) r.room.group.visible = false
    }
    this._lampTarget = 0
    this.interiors.lamp.intensity = 0
    return { visible, lamp: +lamp.toFixed(2) }
  }

  _pauseTest() {
    const d = this.doors.find((x) => x.group)
    if (!d) return { frozen: false, reason: 'no doors' }
    const before = d.progress
    this.paused = true
    for (let i = 0; i < 40; i++) this.update(1 / 30, this._camera)
    const frozen = d.progress === before
    this.paused = false
    return { frozen, before, after: d.progress }
  }
}
