// doors.js — Phase 3B: real doorways, cut into the buildings the hero
// corridor touches, and walk-in interiors with no keypress and no teleport.
//
// What this replaces: interiors.js's E-at-a-marked-threshold entry, which was
// honest about the geometry (the shells were solid) but is now the most
// visible piece of honesty debt left — the HANDOFF calls it out verbatim.
//
// What this does, per configured building:
//
//   1. Cut a real rectangular opening into the building's baked tile wall at
//      street level (exact 2D rect subtraction in the wall plane, doors-math).
//      The walk collider probes the actual tile meshes, so a real hole in the
//      mesh is a real hole in the collision: no hit filter, no fake doorway.
//   2. Punch the matching opening in the room's glazed entrance wall.
//   3. Build the door assembly in the opening: frame (jambs, header, sill),
//      an automatic sliding leaf with a glass pane, a header track, and a lit
//      ceiling panel over the threshold. All procedural, in the same palette
//      as the authored interiors — no third-party asset enters the build.
//   4. Run a door state machine per doorway: closed -> opening -> open ->
//      closing -> closed, driven by a trigger volume; an obstruction that
//      reopens a closing door; a dwell that lets the player pass; a pause
//      freeze; and persisted state across reloads.
//   5. Detect the player crossing the wall plane through the opening and flip
//      interiors.inside physically — the camera never jumps, and walking back
//      out reverses it (reverse traversal).
//   6. Preload the interior when the player is near the threshold: the room
//      group becomes visible and the interior lamp ramps up before the
//      threshold is crossed, so the walk-in is continuous and there is no
//      black void behind the opening.
//   7. Physical lift rides for the interior link thresholds (HQ lobby <->
//      Floor 45, home lobby <-> penthouse) in the corridor's own cab, so the
//      interior transitions that remain are rides, not teleports.
//
// The corridor buildings are configured in data-driven form
// (data/doors/doors.json, generated by scripts/phase2/68_build_doors.py) so
// the same pipeline can be pointed at the ~660 subway-adjacent and
// ground-floor-retail buildings later. Nothing here hard-codes a building.
//
// Verification lives in verify() (measured numbers, per HANDOFF §0) and the
// headless run in scripts/qa/doorcheck-run.mjs.

import * as THREE from 'three'
import {
  cutTriangle, rectsOverlap, polyBox,
  triNormal3, wallFrame, framePoint, frameProject,
} from './doors-math.js'

// ---- the authored room frame ----------------------------------------------
//
// Everything in this file is written in the *authored* room frame, the one
// 60_interiors.py builds in and the HANDOFF §4 documents: +x into the room,
// +y to the left along the entrance wall, +z up.
//
// That is NOT the room group's own local frame. The glTF exporter maps
// Blender (x, y, z) -> (x, z, -y), so the group's local axes are
// (x into the room, y up, z along the wall to the right), and
// interiors.place() keeps the conversion in exactly one place: room.local().
//
// Applying that swap zero times is P2-056 all over again, and it shipped
// here: doors.js fed authored vectors straight to group.localToWorld(), so
// "1.7 m up" became 1.7 m sideways. Measured, on all six rooms,
// room.local(0,0,1.7) and group.localToWorld(0,0,1.7) differed by exactly
// 1.70 m of height — which put every walk-in 1.70 m to the side of a 2.20 m
// opening, 0.60 m past its edge, walking into uncut wall. The trace: the
// camera pinned at room-local x = -0.721 m for 65 consecutive frames with
// the door fully open.
//
// So: authored coordinates cross into group space through authToLocal() and
// come back through localToAuth(), and nowhere else. The door assembly gets
// the same swap as a single -90 deg rotation about x on its own child group,
// which is the matrix form of (x, y, z) -> (x, z, -y).

// Authored (x into, y left, z up) -> room-group local (x into, y up, z right).
export function authToLocal(x, y, z, out) { return out.set(x, z, -y) }

// Room-group local -> authored.
export function localToAuth(v, out) { return out.set(v.x, -v.z, v.y) }

// The rotation that carries an authored-frame child into room-group space.
export const AUTHORED_ROT_X = -Math.PI / 2

// ---- doorway geometry (shared defaults; config can override) --------------
const WALL_W = 2.2          // opening cut in the building wall
const WALL_H = 2.5
const GLASS_W = 1.76        // opening cut in the room's glazed wall
const GLASS_H = 2.4
const GLASS_SILL = 0.22     // clear the authored threshold bar
const BAY_Y = 1.0           // room-local y of the door bay centre (between
                            // the authored mullion grid at 2 m pitch)
const LEAF_W = 1.76         // sliding leaf width (fits the glass opening)
const LEAF_H = 2.36
const LEAF_Z = 0.08         // leaf plane inset from the wall face
const SILL = 0.08
const TRACK_Z = 2.5         // header track height

// ---- door behaviour --------------------------------------------------------
// Leaf travel. 1.76 m in 1.1 s is 1.6 m/s — brisk, and about what a real
// automatic entrance does. It has to beat the walk: the trigger reaches 5 m,
// the player covers that in 1.19 s at WALK speed, and a leaf still sliding
// when they arrive gets shoved out of the way by the collider instead —
// measured at a 0.79 m single-frame displacement against a 0.5 m budget.
const OPEN_S = 1.1
const CLOSE_S = 1.6
const DWELL_S = 3.5         // how long the door waits after the player leaves
// Room-local x span of the trigger volume, measured from the door plane.
//
// Outward reach: an automatic door's sensor sees you coming. At 2.3 m the
// player covered the approach in 0.55 s against the old 2.2 s slide, so they
// always arrived at a quarter-open leaf and were shoved sideways by the
// collider. 5 m of reach against a 1.1 s slide leaves the leaf parked before
// the player gets there.
//
// Inward reach: the volume has to cover the room side too, or the door shuts
// behind the player and will not let them out again. Measured: the reverse
// traversal never crossed in 181 frames at three of the four doorways.
const TRIGGER_X = [-5.0, 2.6]
const TRIGGER_MARGIN_Y = 0.95
const TRIGGER_Z = [-0.5, 3.2]
const OBSTRUCT_MARGIN = 0.45     // player body radius, applied to the leaf box
const PRELOAD_R = 9.0           // interior shown + lamp up inside this range
const CUT_R = 400.0             // wall cut applied once the player is this close
const CUT_RETRY_MS = 500        // back-off between failed cut attempts
const FRONTAGE_PASSES = 4       // rotate/re-resolve until the frontage settles
const RAY_STANDOFF = 60.0       // how far out the wall-finding ray starts
const PASSAGE_PAD = 0.15        // the passage clears wider than the door leaf
const WALK_START = 6.0          // where a walk test begins, outside the trigger
const PASSAGE_RECT = {
  u0: -WALL_W / 2 - PASSAGE_PAD, u1: WALL_W / 2 + PASSAGE_PAD,
  v0: -PASSAGE_PAD, v1: WALL_H + PASSAGE_PAD,
}
const APPROACH_R = 6.0          // the approach to a doorway must be this clear
const ENTER_MARGIN = 0.18       // crossing hysteresis at the wall plane
const WALL_GAP = 0.35           // room glazed wall sits this far inside the wall
const RECESS_WALL_DIST = 5.0    // fallback only; the podium front is measured
// How far along the wall's own normal a face may sit and still belong to this
// doorway. The wall frame is an infinite plane and Manhattan's facades are all
// parallel, so without this the cut punches phantom doorways through every
// building down the block that projects into the same (u, v).
const WALL_BAND = { min: -1.6, max: 1.6 }
// The render probe: how far past the door plane must be clear, and how far
// the ray runs before it stops caring. 3 m of clear room behind the opening
// is a doorway you can walk through; the rooms are 12-15 m deep.
const PROBE_CLEAR = 3.0
const ROOM_DEPTH_PROBE = 8.0

// ---- persistence -----------------------------------------------------------
const SAVE_KEY = 'manhattan.doors.v1'

// ---- palette, matching scripts/phase2/60_interiors.py ----------------------
const METAL = [0.145, 0.148, 0.152]
const WALL_DARK = [0.075, 0.072, 0.070]
const PANEL_LIT = [0.90, 0.88, 0.82]
const GLASS = [0.075, 0.090, 0.105]

// ---------------------------------------------------------------------------
// procedural mesh helpers (vertex-coloured boxes, in the house style)
// ---------------------------------------------------------------------------

function boxMesh(cx, cy, cz, sx, sy, sz, color, material) {
  const hx = sx * 0.5; const hy = sy * 0.5; const hz = sz * 0.5
  const corners = [
    [cx - hx, cy - hy, cz - hz], [cx + hx, cy - hy, cz - hz],
    [cx + hx, cy + hy, cz - hz], [cx - hx, cy + hy, cz - hz],
    [cx - hx, cy - hy, cz + hz], [cx + hx, cy - hy, cz + hz],
    [cx + hx, cy + hy, cz + hz], [cx - hx, cy + hy, cz + hz],
  ]
  const quads = [
    [3, 2, 1, 0], [5, 6, 7, 4], [1, 5, 4, 0],
    [2, 6, 5, 1], [3, 7, 6, 2], [0, 4, 7, 3],
  ]
  const positions = []
  const colors = []
  for (const q of quads) {
    for (const i of q) {
      positions.push(...corners[i])
      colors.push(...color)
    }
  }
  const g = new THREE.BufferGeometry()
  g.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3))
  g.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3))
  g.computeVertexNormals()
  const m = new THREE.Mesh(g, material)
  m.castShadow = false
  m.receiveShadow = true
  return m
}

// ---------------------------------------------------------------------------
// mesh cutting
// ---------------------------------------------------------------------------

// Remove only the triangles lying *wholly* inside `box` — a containment test,
// never an AABB-overlap test. Overlap is what the first pass of this file did
// and it is far too coarse against merged tile geometry, where one triangle
// can be a whole ground-to-roof wall quad: a face that merely reaches into
// the doorway volume (a neighbour's wall running past it) must keep its
// geometry, and only what is actually in the way comes out. `allow(bid)`
// gates which building ids may be removed.
export function cutContained(geometry, box, allow = () => true) {
  const pos = geometry.attributes.position
  const bidAttr = geometry.attributes._bid || geometry.attributes._BID
  const idx = geometry.index
  const tris = idx ? idx.count / 3 : pos.count / 3
  const keep = []
  let removed = 0
  for (let t = 0; t < tris; t++) {
    const a = idx ? idx.getX(t * 3) : t * 3
    const b = idx ? idx.getX(t * 3 + 1) : t * 3 + 1
    const c = idx ? idx.getX(t * 3 + 2) : t * 3 + 2
    let inside = true
    for (const i of [a, b, c]) {
      const x = pos.getX(i); const y = pos.getY(i); const z = pos.getZ(i)
      if (x < box.min[0] || x > box.max[0] || y < box.min[1] ||
          y > box.max[1] || z < box.min[2] || z > box.max[2]) {
        inside = false
        break
      }
    }
    if (inside && bidAttr && !allow(Math.round(bidAttr.getX(a)))) inside = false
    if (inside) removed++
    else keep.push([a, b, c])
  }
  if (!removed) return { geometry, removed: 0 }
  const out = cloneGeometry(geometry)
  const outIdx = []
  for (const [a, b, c] of keep) outIdx.push(a, b, c)
  out.setIndex(outIdx)
  out.computeBoundingSphere()
  return { geometry: out, removed }
}

// Punch a rectangular hole in a room's glazed entrance wall.
//
// The glaze is authored as a plane at the room's x ~ 0, so this is the same
// exact 2D rect subtraction the building wall gets (doors-math), done in the
// wall's own (u, v) = (mesh-local z along the wall, mesh-local y up).
//
// Dropping triangles by AABB cannot do this job. The lobby's glaze is a
// *single* 24 m quad, so removing every triangle whose AABB touches the door
// box deleted the entire pane — measured at 0 glaze triangles remaining on
// all four doorways, which is not a doorway, it is a missing wall. `rect` is
// in mesh-local (z, y);
// only faces within xMax of the entrance plane are considered, so a room
// whose glaze wraps a second wall keeps that wall.
export function cutGlazeRect(geometry, rect, xMax = 0.5) {
  const pos = geometry.attributes.position
  const idx = geometry.index
  const tris = idx ? idx.count / 3 : pos.count / 3
  const outTris = []
  const newVerts = []
  const newNorms = []
  const newCols = []
  const nrm = geometry.attributes.normal
  const col = geometry.attributes.color
  let cut = 0
  let removed = 0

  for (let t = 0; t < tris; t++) {
    const a = idx ? idx.getX(t * 3) : t * 3
    const b = idx ? idx.getX(t * 3 + 1) : t * 3 + 1
    const c = idx ? idx.getX(t * 3 + 2) : t * 3 + 2
    const xs = [pos.getX(a), pos.getX(b), pos.getX(c)]
    if (Math.max(...xs) > xMax) { outTris.push([a, b, c]); continue }
    // (u, v) = (along the wall, up)
    const tri = [
      [pos.getZ(a), pos.getY(a)],
      [pos.getZ(b), pos.getY(b)],
      [pos.getZ(c), pos.getY(c)],
    ]
    if (!rectsOverlap(polyBox(tri), rect)) { outTris.push([a, b, c]); continue }
    const pieces = cutTriangle(tri, rect)
    if (pieces === null) { outTris.push([a, b, c]); continue }
    if (!pieces.length) { removed++; continue }
    cut++

    // the entrance plane's x is whatever this face sits on (0.02 authored),
    // taken from the face itself so a slightly offset pane stays put
    const xPlane = (xs[0] + xs[1] + xs[2]) / 3
    const n0 = nrm ? [nrm.getX(a), nrm.getY(a), nrm.getZ(a)] : null
    const c0 = col ? [col.getX(a), col.getY(a), col.getZ(a)] : null
    const base = pos.count + newVerts.length / 3
    let k = 0
    for (const piece of pieces) {
      const off = k
      for (const [u, v] of piece) {
        newVerts.push(xPlane, v, u)
        if (n0) newNorms.push(n0[0], n0[1], n0[2])
        if (c0) newCols.push(c0[0], c0[1], c0[2])
        k++
      }
      for (let i = 1; i < piece.length - 1; i++) {
        outTris.push([base + off, base + off + i, base + off + i + 1])
      }
    }
  }

  if (!cut && !removed) return { geometry, cut: 0, removed: 0, kept: tris }
  const out = cloneGeometry(geometry)
  const nv = newVerts.length / 3
  extendAttribute(out.attributes.position, nv, (i) => newVerts[i])
  if (out.attributes.normal) {
    extendAttribute(out.attributes.normal, nv, (i) => newNorms[i] ?? 0)
  }
  if (out.attributes.color) {
    extendAttribute(out.attributes.color, nv, (i) => newCols[i] ?? 1)
  }
  for (const [name, attr] of Object.entries(out.attributes)) {
    if (name === 'position' || name === 'normal' || name === 'color') continue
    extendAttribute(attr, nv, null)
  }
  const outIdx = []
  for (const [a, b, c] of outTris) outIdx.push(a, b, c)
  out.setIndex(outIdx)
  out.computeBoundingSphere()
  out.computeBoundingBox()
  return { geometry: out, cut, removed, kept: outTris.length }
}

// Grow a BufferAttribute by `extra` items, filling from fillFn (index into
// the appended run) or with zeroes.
export function extendAttribute(attr, extra, fillFn) {
  const item = attr.itemSize
  const old = attr.array
  const arr = new (old.constructor)(old.length + extra * item)
  arr.set(old)
  for (let i = 0; i < extra * item; i++) {
    arr[old.length + i] = fillFn ? fillFn(i) : 0
  }
  attr.array = arr
  attr.count = arr.length / item
  attr.needsUpdate = true
  return attr
}

// Clone a geometry's attributes into a new geometry. The caller re-indexes.
export function cloneGeometry(geometry) {
  const out = new THREE.BufferGeometry()
  for (const [name, attr] of Object.entries(geometry.attributes)) {
    out.setAttribute(name, attr.clone())
  }
  return out
}

// Cut a rectangular doorway out of the wall faces of one building inside a
// merged tile mesh. `bidSet` maps vertex index -> belongs to the building
// (with .bid on it); `frame` is the wall frame (world); `rect` is the door
// rect in (u, v). Returns { geometry, cut, removed } — the new geometry, or
// the same geometry when nothing was cut. The appended split vertices copy
// the colour of the face they came from, so the facade shading is seamless.
//
// opts.band = { min, max } bounds how far along the frame normal a face may
// sit and still be cut. Without it the frame is an infinite plane: Manhattan's
// facades are all parallel to each other, so a door rect punched "in the wall"
// also punches phantom doorways through every parallel facade down the block
// that happens to project into the same (u, v). Always pass a band.
//
// Faces are cut whichever way they are wound, as long as they are roughly
// parallel to the wall (|dot| > 0.5). The first pass cut only faces whose
// normal *opposed* the frame's — but the frame is built from a face of that
// same wall, so its own normal scores +1 and the wall the doorway is in was
// the one thing the cut skipped. Measured: 2 of 48 building faces reached the
// facing test at the tower lobby and both were rejected by it. Localisation
// is the band's and the aabb's job, not the winding's; a doorway passage has
// to clear whatever is in it, including a neighbour's wall wound back toward
// the door (the market's block shares its outline with an adjacent school).
//
// opts.aabb = { min, max } is the cheap early-out and should always be given.
// A resident tile mesh holds ~10^5 triangles and its bounding box spans a
// 1,400 m tile, so without a per-triangle box test every doorway pays normal
// dots and plane projections over the whole tile — measured as minutes per
// cut, which is what turned the passage sweep into a hang.
export function cutWallInMesh(geometry, bidSet, frame, rect, opts = {}) {
  const band = opts.band || null
  const aabb = opts.aabb || null
  const pos = geometry.attributes.position
  const nrm = geometry.attributes.normal
  const col = geometry.attributes.color
  const idx = geometry.index
  const tris = idx ? idx.count / 3 : pos.count / 3

  const v = (i, out) => {
    out[0] = pos.getX(i); out[1] = pos.getY(i); out[2] = pos.getZ(i)
    return out
  }
  const p0 = [0, 0, 0]; const p1 = [0, 0, 0]; const p2 = [0, 0, 0]
  const outTris = []
  const newVerts = []
  const newNorms = []
  const newCols = []
  const newBids = []
  const srcBid = geometry.attributes._bid || geometry.attributes._BID
  let cut = 0
  let removed = 0
  // Why faces were passed over. A cut that reports zero is otherwise silent
  // about whether it found no building, no wall facing the right way, nothing
  // in the depth band, or nothing overlapping the rect — four very different
  // bugs. Cheap counters beat re-deriving it from the outside.
  // missAxis is a bitmask tally (1 = x, 2 = y, 4 = z) of which axis put a
  // face outside the door box — which is the difference between "the frame is
  // in the wrong place" and "the frame is in the wrong coordinate space".
  const why = { total: tris, mine: 0, box: 0, facing: 0, band: 0, rect: 0,
    missAxis: {} }

  for (let t = 0; t < tris; t++) {
    const a = idx ? idx.getX(t * 3) : t * 3
    const b = idx ? idx.getX(t * 3 + 1) : t * 3 + 1
    const c = idx ? idx.getX(t * 3 + 2) : t * 3 + 2
    if (!bidSet.has(a) || !bidSet.has(b) || !bidSet.has(c)) {
      outTris.push([a, b, c])
      continue
    }
    why.mine++
    v(a, p0); v(b, p1); v(c, p2)
    if (aabb) {
      let miss = 0
      for (let k = 0; k < 3; k++) {
        if (Math.max(p0[k], p1[k], p2[k]) < aabb.min[k] ||
            Math.min(p0[k], p1[k], p2[k]) > aabb.max[k]) {
          miss |= (1 << k)
        }
      }
      if (miss) {
        why.missAxis[miss] = (why.missAxis[miss] || 0) + 1
        outTris.push([a, b, c])
        continue
      }
    }
    why.box++
    const n = triNormal3(p0, p1, p2)
    const dot = n[0] * frame.normal[0] + n[1] * frame.normal[1] +
      n[2] * frame.normal[2]
    if (Math.abs(dot) < 0.5) {
      outTris.push([a, b, c])
      continue
    }
    why.facing++
    if (band) {
      // depth along the frame normal, from the face centroid
      const cxm = (p0[0] + p1[0] + p2[0]) / 3 - frame.o[0]
      const cym = (p0[1] + p1[1] + p2[1]) / 3 - frame.o[1]
      const czm = (p0[2] + p1[2] + p2[2]) / 3 - frame.o[2]
      const depth = cxm * frame.normal[0] + cym * frame.normal[1] +
        czm * frame.normal[2]
      if (depth < band.min || depth > band.max) {
        outTris.push([a, b, c])
        continue
      }
    }
    why.band++
    const u0 = frameProject(frame, p0)
    const u1 = frameProject(frame, p1)
    const u2 = frameProject(frame, p2)
    const tb = polyBox([u0, u1, u2])
    if (!rectsOverlap(tb, rect)) { outTris.push([a, b, c]); continue }
    why.rect++

    const pieces = cutTriangle([u0, u1, u2], rect)
    if (pieces === null) { outTris.push([a, b, c]); continue }
    if (!pieces.length) { removed++; continue }
    cut++

    // The kept pieces, fanned into triangles and appended as their own
    // vertices.
    //
    // This used to build a fan index over a shared vertex list and then emit
    // the triangles as [base + i, base + i + 1, base + i + 2] with `i` running
    // over the fan's *values* rather than its positions — so the rebuilt faces
    // referenced whatever vertices happened to sit at those offsets. The
    // result is geometry that has nothing to do with the wall, and some of it
    // lands back across the opening: measured, a collision probe from inside
    // the home lobby hit tile geometry at (u, v) = (0.00, 0.99), dead centre
    // of a 2.2 x 2.5 m doorway that rays at other heights passed straight
    // through. Emitting three fresh vertices per triangle costs a few
    // duplicates and cannot be indexed wrong.
    const c0 = col ? [col.getX(a), col.getY(a), col.getZ(a)] : null
    // the face's own building id, not the caller's: a passage cut runs over
    // the *neighbours'* faces, and stamping them with the target's bid would
    // relabel another building's facade (Draco quantises _BID, so round it —
    // P2-060)
    const b0 = srcBid ? Math.round(srcBid.getX(a))
      : (bidSet.bid ?? 0)
    for (const piece of pieces) {
      for (let i = 1; i < piece.length - 1; i++) {
        const base = pos.count + newVerts.length / 3
        for (const [u, vv] of [piece[0], piece[i], piece[i + 1]]) {
          const p = framePoint(frame, u, vv)
          newVerts.push(p[0], p[1], p[2])
          newNorms.push(n[0], n[1], n[2])
          newBids.push(b0)
          if (c0) newCols.push(c0[0], c0[1], c0[2])
        }
        outTris.push([base, base + 1, base + 2])
      }
    }
  }

  if (!cut && !removed) return { geometry, cut: 0, removed: 0, why }

  const out = cloneGeometry(geometry)
  const posA = out.attributes.position
  const nrmA = out.attributes.normal
  const colA = out.attributes.color
  const nv = newVerts.length / 3

  const extend = extendAttribute
  extend(posA, nv, (i) => newVerts[i])
  if (nrmA) extend(nrmA, nv, (i) => newNorms[i])
  if (colA) extend(colA, nv, (i) => newCols[i])
  const bidName = out.attributes._bid ? '_bid' : '_BID'
  if (bidName && out.attributes[bidName]) {
    extend(out.attributes[bidName], nv, (i) => newBids[i])
  }
  const other = []
  for (const [name, attr] of Object.entries(out.attributes)) {
    if (name === 'position' || name === 'normal' || name === 'color' ||
        name === bidName) continue
    other.push([name, attr])
  }
  for (const [name, attr] of other) extend(attr, nv, null)

  const outIdx = []
  for (const [a, b, c] of outTris) outIdx.push(a, b, c)
  out.setIndex(outIdx)
  out.computeBoundingSphere()
  out.computeBoundingBox()
  return { geometry: out, cut, removed, why }
}

// ---------------------------------------------------------------------------
// the door system
// ---------------------------------------------------------------------------

export class Doors {
  constructor(scene, city, interiors, hq, corridor, streamer) {
    this.scene = scene
    this.city = city
    this.interiors = interiors
    this.hq = hq
    this.corridor = corridor
    this.streamer = streamer
    this.groundY = city?.meta?.land_level_m ?? 12.0
    this.doors = []
    this.ready = false
    this.active = true       // false while the hero corridor owns the camera
    this.paused = false
    this.stats = { doors: 0, cut: 0, open: 0, state: 'idle' }
    this._saved = this._loadSaved()
    this._lampTarget = 0
    this._audio = null
    this._camera = null
    this._controls = null
    this._ride = null
    this._restored = []

    document.addEventListener('visibilitychange', () => {
      this.paused = document.hidden
    })
  }

  setAudio(audio) { this._audio = audio }

  async load(url = '/doors/doors.json') {
    const data = await fetch(url).then((r) => (r.ok ? r.json() : null))
      .catch(() => null)
    if (!data || !Array.isArray(data.doors)) {
      console.warn('[doors] no doors.json; doorways disabled')
      return this
    }
    // The expansion set (68_build_doors.py --expansion, 631 subway-tranche
    // buildings) is generated with runtimeEnabled: false and lives in its own
    // file. If it is ever pointed at this loader by mistake, refuse it: those
    // entries have no interior room, and cutting a hole into a solid building
    // is worse than no doorway. The gate is a room behind the opening, not a
    // flag.
    if (data.runtimeEnabled === false) {
      console.warn('[doors]', url, 'is marked runtimeEnabled: false',
        `(${data.doors.length} entries); doorways disabled`)
      return this
    }
    for (const cfg of data.doors) this._add(cfg)
    for (const d of this.doors) {
      // the interior answers no keypress once its doorway is real
      d.room.doorway = true
      // the wall cut may rotate the room to a clear frontage, and it measures
      // the wall distance the assembly and the crossing plane are placed
      // from, so the assembly is built after it, from the final matrix. Both
      // kinds cut: a recess is a wall like any other (§ _cutWall).
      this._cutWall(d)
      this._buildAssembly(d)
      this._cutRoomGlass(d)
    }
    this.ready = this.doors.length > 0
    this.stats.doors = this.doors.length
    // tiles can arrive after boot; re-cut a door's wall when its tile loads
    this.streamer.onReady.push(() => {
      for (const d of this.doors) if (!d.cut) this._findAndCut(d)
    })
    console.info('[doors]', this.doors.length, 'doorways configured:',
      this.doors.map((d) => `${d.key} (bid ${d.bid})`).join(', '))
    if (this._restored.length) {
      // timing-free evidence for the headless runner's reload check
      window.__doorsBootState = this._restored
    }
    return this
  }

  bind(camera, controls) {
    this._camera = camera
    this._controls = controls
  }

  _add(cfg) {
    // An entrance with no interior behind it stays a closed door. That is the
    // documented behaviour of the `entrance` kind and the reason the ~660
    // expansion set is data-only: the runtime resolves an interior when one
    // exists and cuts nothing when one does not.
    const room = cfg.room
      ? this.interiors.rooms.find((r) => r.key === cfg.room) : null
    if (!room) {
      console.warn('[doors] no interior for', cfg.key,
        cfg.room ?? '(none configured)', '- no opening cut')
      return
    }
    const bayCenter = cfg.bayCenter != null ? cfg.bayCenter : BAY_Y
    const rec = {
      key: cfg.key,
      bid: cfg.bid,
      kind: cfg.kind || 'wall',
      room,
      bayCenter,
      bayY0: bayCenter - GLASS_W / 2,
      bayY1: bayCenter + GLASS_W / 2,
      wallDist: cfg.kind === 'recess'
        ? (cfg.wallDist != null ? cfg.wallDist : RECESS_WALL_DIST) : null,
      state: 'closed',
      progress: 0,
      dwell: 0,
      trigger: false,
      inside: false,
      near: false,
      cut: false,
      mesh: null,
      leaf: null,
      group: null,
      soundAt: 0,
      prevLocalX: null,
    }
    if (this._saved && this._saved.doors && this._saved.doors[cfg.key]) {
      rec.state = 'open'
      rec.progress = 1
      rec.dwell = DWELL_S
      this._restored.push({ key: cfg.key, state: rec.state })
    }
    this.doors.push(rec)
  }

  // ---- wall discovery -----------------------------------------------------

  // Which vertices of a merged tile mesh belong to `bid`, as a predicate.
  // Draco quantises _BID so it decodes as 34686.0039 — always round (P2-060).
  _buildingVerts(mesh, bid) {
    const attr = mesh.geometry.attributes._bid || mesh.geometry.attributes._BID
    if (!attr) return null
    return { has: (i) => Math.round(attr.getX(i)) === bid, bid }
  }

  // Does this mesh hold any of `bid`? Early-exits on the first match rather
  // than materialising a vertex set, which _findMesh would otherwise pay for
  // every candidate mesh in every resident tile.
  _hasBuilding(mesh, bid) {
    const attr = mesh.geometry.attributes._bid || mesh.geometry.attributes._BID
    if (!attr) return false
    for (let i = 0; i < attr.count; i++) {
      if (Math.round(attr.getX(i)) === bid) return true
    }
    return false
  }

  // Every vertex of a standalone mesh. The HQ tower is its own object rather
  // than a merged tile, so it has no _bid to select on — the whole mesh is
  // the building. A predicate rather than a Set: cutWallInMesh only ever asks
  // `has(i)`, and materialising one entry per vertex of a city-scale mesh is
  // pure allocation.
  _allVerts(mesh, bid) {
    if (!mesh.geometry.attributes.position.count) return null
    return { has: () => true, bid }
  }

  // The mesh a doorway cuts into, and the vertex set that selects its
  // building inside it.
  _cutTarget(d) {
    if (d.kind === 'recess') {
      const mesh = this.hq && this.hq.tower && this.hq.tower.children[0]
      if (!mesh) return null
      return { mesh, verts: this._allVerts(mesh, d.bid), standalone: true }
    }
    const b = d.room.building
    const wx = b ? b.x : this.city.x(d.bid)
    const wz = b ? -b.y : -this.city.y(d.bid)
    const mesh = this._findMesh(d.bid, wx, wz)
    if (!mesh) return null
    return { mesh, verts: this._buildingVerts(mesh, d.bid), standalone: false }
  }

  // A world wall frame expressed in a mesh's own coordinates.
  //
  // Tile meshes are baked in world space and sit at identity, so the cut can
  // read their positions directly. The HQ tower is not: it is placed by hq.js
  // with the site's origin and yaw, and its geometry runs 0..46.7 m in x. Its
  // doorway was being cut with a world-space frame against local-space
  // vertices — 1,828 of 1,828 faces rejected, every time.
  _frameInMeshSpace(frame, mesh) {
    mesh.updateMatrixWorld(true)
    const e = mesh.matrixWorld.elements
    const identity = Math.abs(e[0] - 1) < 1e-9 && Math.abs(e[5] - 1) < 1e-9 &&
      Math.abs(e[10] - 1) < 1e-9 && Math.abs(e[12]) < 1e-9 &&
      Math.abs(e[13]) < 1e-9 && Math.abs(e[14]) < 1e-9 &&
      Math.abs(e[1]) < 1e-9 && Math.abs(e[2]) < 1e-9 && Math.abs(e[4]) < 1e-9
    if (identity) return frame
    const inv = new THREE.Matrix4().copy(mesh.matrixWorld).invert()
    const rot = new THREE.Matrix3().setFromMatrix4(inv)
    const pt = (v) => new THREE.Vector3(v[0], v[1], v[2])
      .applyMatrix4(inv).toArray()
    const dir = (v) => new THREE.Vector3(v[0], v[1], v[2])
      .applyMatrix3(rot).normalize().toArray()
    return {
      o: pt(frame.o),
      uaxis: dir(frame.uaxis),
      vaxis: dir(frame.vaxis),
      normal: dir(frame.normal),
    }
  }

  // The height the doorway's sill sits at: the room's own floor, not the land
  // level. The HQ lobby stands on a 0.60 m podium plinth (12.60 against a
  // 12.00 pavement); cutting its opening from the pavement would leave a lip
  // across the threshold.
  _sillY(d) {
    return d.room.group.position.y
  }

  _meshBox(mesh) {
    const g = mesh.geometry
    if (!g.boundingSphere) g.computeBoundingSphere()
    if (!g.boundingBox) g.computeBoundingBox()
    return g.boundingBox
  }

  _findMesh(bid, wx, wz) {
    for (const group of this.streamer.pickables()) {
      let found = null
      group.traverse((o) => {
        if (found || !o.isMesh) return
        const g = o.geometry
        if (!(g.attributes._bid || g.attributes._BID)) return
        const bb = this._meshBox(o)
        if (wx < bb.min.x - 2 || wx > bb.max.x + 2 ||
            wz < bb.min.z - 2 || wz > bb.max.z + 2) return
        const s = g.boundingSphere
        if (Math.hypot(wx - s.center.x, wz - s.center.z) > s.radius + 2) return
        if (this._hasBuilding(o, bid)) found = o
      })
      if (found) return found
    }
    return null
  }

  // The street-facing wall of the building nearest the room's doorway, in
  // world space: { frame, wallDist } where the frame's origin is the door
  // axis projected onto the wall plane at ground level. Candidate walls are
  // tried nearest-first, and a wall whose approach is concealed by another
  // building (adjacent footprints overlap in the OSM data) is rejected --
  // a doorway that opens onto a neighbour's wall is not a doorway. Null when
  // no wall face answers.
  // The wall the player will actually meet, found by one ray along the way in
  // rather than by scanning candidates.
  //
  // _findWall picks the candidate whose *centroid* is nearest the door axis,
  // then takes the perpendicular foot on that face's plane. On a tower whose
  // wall quads are tens of metres across, the nearest centroid can belong to a
  // plane 15 m away — measured, both tower lobbies ended up standing 15.06 m
  // and 4.48 m from the wall their doorway was cut into. A ray cannot make
  // that mistake: whatever it hits first going in is the wall in the way.
  // It is also O(1), where the candidate sweep costs an approach raycast per
  // ground-band triangle (1,828 of them for the HQ tower, which hung the page).
  //
  // `bid` filters hits in a merged tile mesh to the target building; a
  // standalone mesh (the HQ tower) passes null.
  _findWallByRay(d, mesh, bid = null) {
    const dir = this._doorDir(d)
    const sillY = this._sillY(d)
    const attr = mesh.geometry.attributes._bid || mesh.geometry.attributes._BID
    for (const z of [1.2, 0.6, 1.8]) {
      const origin = this.roomToWorld(d, -RAY_STANDOFF, d.bayCenter, z)
      const rc = new THREE.Raycaster(origin, dir, 0, RAY_STANDOFF * 2)
      let hit = null
      for (const h of rc.intersectObject(mesh, true)) {
        if (!h.face) continue
        if (bid != null && attr &&
            Math.round(attr.getX(h.face.a)) !== bid) continue
        hit = h
        break
      }
      if (!hit) continue
      const n = hit.face.normal.clone()
        .applyNormalMatrix(
          new THREE.Matrix3().getNormalMatrix(hit.object.matrixWorld))
        .normalize()
      // the frame normal points out of the building, against the walk-in
      if (n.dot(dir) > 0) n.negate()
      const frame = wallFrame([n.x, n.y, n.z])
      const axis = this.roomToWorld(d, 0, d.bayCenter, 0)
      axis.y = sillY
      const t = -((axis.x - hit.point.x) * n.x + (axis.y - hit.point.y) * n.y +
        (axis.z - hit.point.z) * n.z)
      frame.o = [axis.x + n.x * t, sillY, axis.z + n.z * t]
      // how far in front of the room origin the wall face is, along +x
      const local = this._local(d, hit.point, new THREE.Vector3())
      return { frame, wallDist: Math.abs(local.x) }
    }
    return null
  }

  _findWall(d, mesh, set = null) {
    const pos = mesh.geometry.attributes.position
    const idx = mesh.geometry.index
    set = set || this._buildingVerts(mesh, d.bid)
    if (!set) return null
    const sillY = this._sillY(d)
    const doorAxis = this.roomToWorld(d, 0, d.bayCenter, 0)
    doorAxis.y = sillY

    const p0 = [0, 0, 0]; const p1 = [0, 0, 0]; const p2 = [0, 0, 0]
    const candidates = []
    const tris = idx ? idx.count / 3 : pos.count / 3
    for (let t = 0; t < tris; t++) {
      const a = idx ? idx.getX(t * 3) : t * 3
      const b = idx ? idx.getX(t * 3 + 1) : t * 3 + 1
      const c = idx ? idx.getX(t * 3 + 2) : t * 3 + 2
      if (!set.has(a) || !set.has(b) || !set.has(c)) continue
      p0[0] = pos.getX(a); p0[1] = pos.getY(a); p0[2] = pos.getZ(a)
      p1[0] = pos.getX(b); p1[1] = pos.getY(b); p1[2] = pos.getZ(b)
      p2[0] = pos.getX(c); p2[1] = pos.getY(c); p2[2] = pos.getZ(c)
      if (Math.max(p0[1], p1[1], p2[1]) < sillY - 0.5 ||
          Math.min(p0[1], p1[1], p2[1]) > sillY + WALL_H + 0.5) {
        continue
      }
      const n = triNormal3(p0, p1, p2)
      if (n[1] > 0.5 || n[1] < -0.5) continue   // walls only, not roofs/floors
      const cx = (p0[0] + p1[0] + p2[0]) / 3
      const cz = (p0[2] + p1[2] + p2[2]) / 3
      const d2 = (cx - doorAxis.x) ** 2 + (cz - doorAxis.z) ** 2
      // every ground-band wall is a candidate, not just the ones facing the
      // room's current frontage: when that frontage is concealed by an
      // adjacent footprint the room rotates to the next clear wall instead
      candidates.push({ n, p: [cx, p0[1], cz], d2 })
    }
    candidates.sort((a, b) => a.d2 - b.d2)
    for (const cand of candidates) {
      const frame = wallFrame(cand.n)
      // The door axis, projected onto the candidate's plane: subtract the
      // signed distance along the normal from the axis itself.
      //
      // This used to start from the candidate face's centroid and step along
      // the normal, which lands the origin *off* the plane by the whole wall
      // distance and leaves it wherever the nearest triangle happened to be —
      // measured at 25.0 m from the room's own doorway for the home lobby,
      // with the frame origin 11.73 m clear of the wall. Everything derived
      // from the frame inherits that: the cut rect, the door box, the
      // assembly. The opening was being cut at the nearest wall triangle
      // rather than in front of the door.
      const dn = (doorAxis.x - cand.p[0]) * cand.n[0] +
        (doorAxis.y - cand.p[1]) * cand.n[1] +
        (doorAxis.z - cand.p[2]) * cand.n[2]
      const proj = [
        doorAxis.x - cand.n[0] * dn,
        doorAxis.y - cand.n[1] * dn,
        doorAxis.z - cand.n[2] * dn,
      ]
      frame.o = [proj[0], sillY, proj[2]]
      if (!this._approachClear(d, frame)) continue
      return { frame, wallDist: Math.abs(dn) }
    }
    return null
  }

  // Is the approach to a wall frame clear for APPROACH_R metres? A ray from
  // just outside the wall toward the street must not meet another building's
  // wall -- adjacent footprints overlap in the OSM data, and a doorway that
  // opens onto a neighbour is worse than no doorway. Buildings share merged
  // tile meshes, so the test is by building id, never by object identity:
  // the same mesh holds both the target building and the neighbour.
  _approachClear(d, frame) {
    const raycaster = new THREE.Raycaster()
    const ox = frame.o[0] + frame.normal[0] * 0.4
    const oz = frame.o[2] + frame.normal[2] * 0.4
    raycaster.set(
      new THREE.Vector3(ox, frame.o[1] + 1.5, oz),
      new THREE.Vector3(frame.normal[0], 0, frame.normal[2]))
    raycaster.far = APPROACH_R
    const seen = []
    for (const group of this.streamer.pickables()) {
      const hits = raycaster.intersectObjects(group, true)
      for (const h of hits) {
        const attr = h.object.geometry.attributes._bid ||
          h.object.geometry.attributes._BID
        if (!attr) continue
        const bid = Math.round(attr.getX(h.face ? h.face.a : 0))
        seen.push({ bid, d: +h.distance.toFixed(2),
          obj: h.object.name || h.object.type })
        if (bid !== d.bid) {
          d.lastClear = { ok: false, seen,
            origin: [+ox.toFixed(1), 1.5, +oz.toFixed(1)] }
          return false
        }
      }
    }
    d.lastClear = { ok: true, seen,
      origin: [+ox.toFixed(1), 1.5, +oz.toFixed(1)] }
    return true
  }

  _cutWall(d) {
    const target = this._cutTarget(d)
    if (!target || !target.verts) return false
    const mesh = target.mesh
    let wall = target.standalone
      ? this._findWallByRay(d, mesh)
      : this._findWall(d, mesh, target.verts)
    if (!wall) return false
    d.frontageNormal = wall.frame.normal.map((v) => +v.toFixed(3))

    // A recess doorway is anchored by its own building (the HQ podium is
    // placed by hq.js and its lobby's links, shot and lift are authored
    // against it), so it is never rotated or shifted -- but it is cut, like
    // any other wall. The first pass took the podium's authored entrance
    // recess on trust; measured, the podium front is solid across the whole
    // frontage (rays at 1 m spacing from -4 m to +4 m along the wall all hit
    // HQ_tower at the same 0.4 m depth, at every height from 0.3 to 2.2 m).
    // A door placed on that would be a door painted on a wall.
    if (!target.standalone && !d.relocated) {
      // A blocked default frontage (adjacent footprint overlap) means the
      // doorway has to face the clear wall instead: rotate the room so its
      // glazed wall looks out through the chosen opening, then rebase every
      // camera position the corridor and the HUD derive from the room.
      //
      // Rotating moves the door axis, which can make a *different* wall the
      // nearest one — so resolve and rotate until they agree. Doing it once
      // leaves the room facing wall A while the shift below uses wall B's
      // distance, and the two disagree by however far apart the walls are:
      // measured, the tower lobby ended up 15 m clear of its own footprint
      // with the cut landing on nothing.
      let passes = 0
      for (; passes < FRONTAGE_PASSES; passes++) {
        const n = wall.frame.normal
        const yaw = Math.atan2(n[2], -n[0])
        if (Math.abs(yaw - d.room.group.rotation.y) < 1e-6) break
        d.room.group.rotation.y = yaw
        d.room.group.updateMatrixWorld(true)
        d.room.yaw = yaw
        this.interiors.rebase(d.room)
        const next = this._findWall(d, mesh, target.verts)
        if (!next) break
        wall = next
      }
      d.frontagePasses = passes
      d.relocated = true
      // the assembly is built from the room's matrix; a relocation that
      // happens after load (tile arrived late) must rebuild it
      if (d.group) this._buildAssembly(d)
    }
    d.wallDist = wall.wallDist

    // The frontage is chosen; now measure the wall along the way in and stand
    // the room at it.
    //
    // The room is anchored at its building's centre and its authored +x
    // (_doorDir) points *into* the building — the relocation above sets the
    // yaw precisely so, giving doorDir = -normal. So the move toward the
    // frontage is along the wall normal, i.e. **minus** doorDir. Shifting
    // along +doorDir drives the room deeper in instead: measured, the tower
    // lobby went from 9.80 m off its wall to 16.44 m.
    //
    // Everything the cut needs — the rect's centre, the door box, the
    // assembly plane — comes from this frame, so it is resolved from the
    // room's *final* position, and by ray rather than by candidate scan.
    if (!target.standalone) {
      const byRay = this._findWallByRay(d, mesh, d.bid)
      if (byRay) wall = byRay
      if (!d.shifted) {
        const doorDir = this._doorDir(d)
        d.room.group.position.addScaledVector(doorDir,
          -(wall.wallDist - WALL_GAP))
        d.room.group.updateMatrixWorld(true)
        d.shifted = true
      }
      // Once the opening exists the ray flies straight through it and finds
      // nothing, so a re-cut (tile streamed out and back) has to reuse the
      // frame that was resolved when the wall was still solid.
      const settled = this._findWallByRay(d, mesh, d.bid) || d.resolvedWall
      if (settled) wall = settled
      d.resolvedWall = wall
      d.wallDist = wall.wallDist
      // the number that says the room is standing at its own wall: after the
      // shift this must be WALL_GAP, not "somewhere in the building"
      d.shiftResidual_m = +wall.wallDist.toFixed(3)
    } else {
      wall = this._findWallByRay(d, mesh) || d.resolvedWall || wall
      d.resolvedWall = wall
      d.wallDist = wall.wallDist
    }

    // the frame origin is on the door axis, so the cut rect is centred on it
    const rect = { u0: -WALL_W / 2, u1: WALL_W / 2, v0: 0, v1: WALL_H }
    const box = this._doorBox(wall.frame)
    // the target's own geometry may not be in world space (the HQ tower)
    const meshFrame = this._frameInMeshSpace(wall.frame, mesh)
    const r = cutWallInMesh(mesh.geometry, target.verts, meshFrame, rect,
      { band: WALL_BAND, aabb: this._doorBox(meshFrame) })
    if (r.geometry !== mesh.geometry) {
      d.mesh = mesh
      mesh.geometry = r.geometry
      this.stats.cut += r.cut
    }
    d.cut = r.cut > 0 || r.removed > 0
    d.cutFaces = r.cut
    d.removedTris = r.removed
    d.cutWhy = r.why
    d.cutFrame = { o: wall.frame.o.map((v) => +v.toFixed(2)),
      n: wall.frame.normal.map((v) => +v.toFixed(3)),
      box: { min: box.min.map((v) => +v.toFixed(2)),
        max: box.max.map((v) => +v.toFixed(2)) },
      axis: this.roomToWorld(d, 0, d.bayCenter, 0).toArray()
        .map((v) => +v.toFixed(2)) }

    // A passage cut: some footprints in the OSM data overlap their
    // neighbours by a metre or more (the corridor market's block shares its
    // outline with an adjacent school), so the doorway volume may contain
    // another building's wall just inside the target's own.
    //
    // This used to be a blunt AABB-overlap sweep over every tile mesh
    // touching the door volume, dropping any triangle whose box crossed. That
    // is far too coarse in a merged tile mesh: a neighbour's wall quad runs
    // ground to roof, so the whole facade went — and worse, the four exact
    // pieces the cut above had just left around the hole have AABBs touching
    // the box too, so the careful cut was immediately blown out. The doorway
    // must be a doorway, not a demolition.
    //
    // So: the same exact rect subtraction, in the same wall frame, applied to
    // the *other* buildings' faces only (the target's wall is already cut),
    // plus a containment sweep for the faces that are not parallel to the
    // wall and so cannot be rect-subtracted. Both are counted.
    d.passageRemoved = 0
    d.passageCutFaces = 0
    d.passageBoxRemoved = 0
    // The HQ tower is not streamed, so the sweep has to be told about it — and
    // it needs the sweep: its podium reveals are perpendicular to the frontage
    // and so are not touched by the frontage cut, but they are still inside
    // the passage.
    const sweep = [...this.streamer.pickables()]
    if (this.hq && this.hq.tower) sweep.push(this.hq.tower)
    for (const group of sweep) {
      group.traverse((o) => {
        if (!o.isMesh) return
        const g = o.geometry
        // AABB against the door box, not a sphere test: a tile mesh's
        // bounding sphere covers most of the tile, so the loose test dragged
        // every resident mesh through the cut
        if (!g.boundingBox) g.computeBoundingBox()
        const bb = g.boundingBox
        if (bb.max.x < box.min[0] || bb.min.x > box.max[0] ||
            bb.max.y < box.min[1] || bb.min.y > box.max[1] ||
            bb.max.z < box.min[2] || bb.min.z > box.max[2]) return
        let geom = g
        let touched = false
        const others = this._verticesExcept(o, d.bid)
        if (others) {
          // A passage is at least as wide as the door it serves. The
          // neighbour's wall is rarely exactly parallel to the target's, so
          // subtracting the identical rect leaves slivers across the opening
          // — measured, 6 of 15 probe rays still met building 20009 at the
          // market's threshold after an exact-rect passage cut.
          const rc = cutWallInMesh(geom, others, wall.frame, PASSAGE_RECT,
            { band: WALL_BAND, aabb: box })
          if (rc.geometry !== geom) {
            geom = rc.geometry
            touched = true
            d.passageCutFaces += rc.cut
          }
        }
        const rb = cutContained(geom, box, (bid) => bid !== d.bid)
        if (rb.geometry !== geom) {
          geom = rb.geometry
          touched = true
          d.passageBoxRemoved += rb.removed
        }
        if (touched) {
          o.geometry = geom
          d.passageRemoved++
        }
      })
    }
    return d.cut
  }

  // Every vertex in a merged tile mesh that does *not* belong to `bid`, as a
  // predicate. .bid = null so a re-emitted face keeps its own building id
  // rather than being relabelled as the target's.
  _verticesExcept(mesh, bid) {
    const attr = mesh.geometry.attributes._bid || mesh.geometry.attributes._BID
    if (!attr) return null
    return { has: (i) => Math.round(attr.getX(i)) !== bid, bid: null }
  }

  // The doorway volume in world space, as an axis-aligned box: WALL_W plus a
  // jamb margin along the wall, the full door height, and 1.5 m of wall
  // thickness either side of the wall plane.
  _doorBox(frame) {
    const corners = []
    for (const u of [-WALL_W / 2 - 0.2, WALL_W / 2 + 0.2]) {
      for (const v of [-0.1, WALL_H + 0.1]) {
        for (const w of [-1.5, 1.5]) {
          const p = framePoint(frame, u, v)
          corners.push([
            p[0] + frame.normal[0] * w,
            p[1] + frame.normal[1] * w,
            p[2] + frame.normal[2] * w,
          ])
        }
      }
    }
    const min = [Infinity, Infinity, Infinity]
    const max = [-Infinity, -Infinity, -Infinity]
    for (const c of corners) {
      for (let i = 0; i < 3; i++) {
        if (c[i] < min[i]) min[i] = c[i]
        if (c[i] > max[i]) max[i] = c[i]
      }
    }
    return { min, max }
  }

  // A wall door's cut lives in a tile mesh; a tile that streams out and back
  // in brings fresh uncut geometry, so the cut has to be re-applied. The HQ
  // tower is not streamed, so being parented to the scene is enough.
  _meshLive(d) {
    if (!d.mesh || !d.mesh.parent) return false
    return d.kind === 'recess' ? true : !!d.mesh.parent.parent
  }

  _findAndCut(d) {
    if (d.cut && this._meshLive(d)) return
    // The cut walks the tile mesh and raycasts; retrying it every frame while
    // a tile is still arriving costs more than the cut does. Back off.
    const now = performance.now()
    if (d.nextCutAt && now < d.nextCutAt) return
    d.nextCutAt = now + CUT_RETRY_MS
    const before = d.wallDist
    if (this._cutWall(d) && d.wallDist !== before && d.group) {
      // the measured wall distance moved the crossing plane; the assembly is
      // built at that plane, so it has to follow
      this._buildAssembly(d)
    }
  }

  // Punch the door opening in the room's glazed wall. Each room instance has
  // its own cloned geometry (interiors.place clones), so one cut cannot leak
  // into another room that reuses the same authored mesh.
  //
  // The rect is expressed in the glaze mesh's own local axes, which are the
  // group's, not the authored ones: u = mesh z = along the wall (authored +y
  // to the left is mesh -z), v = mesh y = up.
  _cutRoomGlass(d) {
    const rect = {
      u0: -d.bayY1, u1: -d.bayY0,
      v0: GLASS_SILL, v1: GLASS_SILL + GLASS_H,
    }
    d.glazeCut = 0
    d.glazeRemoved = 0
    d.glazeKept = 0
    for (const child of d.room.group.children) {
      if (!child.isMesh || !child.userData.glaze) continue
      const r = cutGlazeRect(child.geometry, rect)
      if (r.geometry !== child.geometry) child.geometry = r.geometry
      d.glazeCut += r.cut
      d.glazeRemoved += r.removed
      d.glazeKept += r.kept
    }
  }

  // ---- door assembly ------------------------------------------------------

  // Where the doorway plane sits in the room's authored x: the face of the
  // wall the opening is cut in. For a shifted room that is WALL_GAP by
  // construction; for a recess it is wherever the podium wall was measured to
  // be (the HQ's was assumed at 5.0 m and is actually 0.4 m, which put the
  // door assembly 4.5 m out in the open plaza with the real wall left solid
  // behind it).
  _wallPlaneX(d) {
    if (d.kind !== 'recess') return -WALL_GAP
    return -(d.wallDist ?? RECESS_WALL_DIST)
  }

  _buildAssembly(d) {
    const room = d.room
    // a late relocation (tile arrived after boot) must rebuild the assembly
    // at the room's final matrix
    if (d.group) {
      this.scene.remove(d.group)
      d.group.traverse((o) => {
        if (o.isMesh) {
          o.geometry.dispose()
          if (Array.isArray(o.material)) o.material.forEach((m) => m.dispose())
          else o.material.dispose()
        }
      })
      d.group = null
      d.leaf = null
    }
    const group = new THREE.Group()
    group.name = `DOOR_${d.key}`
    group.position.copy(room.group.position)
    group.rotation.copy(room.group.rotation)
    this.scene.add(group)
    d.group = group

    // Everything below is authored-frame (+x into, +y left, +z up). This one
    // rotation is the (x, y, z) -> (x, z, -y) swap in matrix form, applied
    // exactly once, so the boxes read the way the room was authored. Without
    // it the assembly came out rotated 90 deg about x: the sliding leaf
    // measured 1.76 m tall instead of 2.36, and the lit ceiling panel sat at
    // 0.17-1.83 m above the pavement instead of 2.66 m.
    const authored = new THREE.Group()
    authored.name = 'authored'
    authored.rotation.x = AUTHORED_ROT_X
    group.add(authored)

    const y0 = d.bayY0
    const y1 = d.bayY1
    const mat = this.interiors.material
    const glass = this.interiors.glassMaterial
    const xWall = this._wallPlaneX(d)

    // ---- frame ------------------------------------------------------------
    const frameG = new THREE.Group()
    frameG.name = 'frame'
    frameG.add(
      boxMesh(xWall, y0 - 0.05, 1.25, 0.18, 0.14, 2.44, METAL, mat),
      boxMesh(xWall, y1 + 0.05, 1.25, 0.18, 0.14, 2.44, METAL, mat),
      boxMesh(xWall, (y0 + y1) / 2, 2.5, 0.18, y1 - y0 + 0.28, 0.16, METAL, mat),
      boxMesh(xWall, (y0 + y1) / 2, SILL / 2, 0.3, y1 - y0 + 0.28, SILL,
        WALL_DARK, mat),
      boxMesh(xWall + LEAF_Z, (y0 + y1) / 2, TRACK_Z + 0.06, 0.1,
        y1 - y0 + 0.4, 0.06, WALL_DARK, mat),
    )
    authored.add(frameG)

    // ---- automatic sliding leaf -------------------------------------------
    // A panel in the wall plane that slides +y: closed it covers the opening,
    // open it parks against the wall beside it — the honest version of an
    // automatic door where no pocket exists in a cut opening. Thin in the
    // room's x (the wall plane), long along y (the slide axis), tall in z.
    const leafG = new THREE.Group()
    leafG.name = 'leaf'
    leafG.add(
      boxMesh(0, LEAF_W / 2, SILL + LEAF_H / 2, 0.08, LEAF_W, LEAF_H,
        METAL, mat),
      boxMesh(0, LEAF_W / 2, SILL + LEAF_H / 2, 0.05, LEAF_W - 0.16,
        LEAF_H - 0.16, GLASS, glass),
      boxMesh(0, LEAF_W - 0.05, SILL + LEAF_H * 0.55, 0.03, 0.06, 0.9,
        METAL, mat),
    )
    leafG.position.set(xWall + LEAF_Z, y0 + 0.02, 0)
    d.leaf = leafG
    authored.add(leafG)

    // ---- lit ceiling panel over the threshold ------------------------------
    authored.add(boxMesh(xWall - 0.1, (y0 + y1) / 2, TRACK_Z + 0.16, 0.5,
      y1 - y0 - 0.1, 0.05, PANEL_LIT, mat))

    group.updateMatrixWorld(true)
  }

  // ---- trigger, crossing, preload -----------------------------------------

  // A world point in the room's *authored* frame: x into the room, y left
  // along the entrance wall, z up from the room floor. Every trigger,
  // crossing, preload and probe below reads these, so the swap happens here
  // and only here.
  _local(d, p, out) {
    return localToAuth(d.room.group.worldToLocal(out.copy(p)), out)
  }

  // The inverse: an authored-frame point of this room, in world space. Public
  // because the headless runner (scripts/qa/doorcheck-run.mjs) places its
  // cameras in the same frame and must not re-derive the swap.
  roomToWorld(d, x, y, z, out = new THREE.Vector3()) {
    return d.room.group.localToWorld(authToLocal(x, y, z, out))
  }

  // World direction of authored +x — into the room, through the doorway.
  // (authored +x is group-local +x, so this one needs no swap; it is here so
  // the two call sites cannot drift apart.)
  _doorDir(d, out = new THREE.Vector3()) {
    return d.room.group.localToWorld(out.set(1, 0, 0))
      .sub(d.room.group.position).normalize()
  }

  _inTrigger(d, camera) {
    const v = this._local(d, camera.position, new THREE.Vector3())
    const xWall = this._wallPlaneX(d)
    return v.x > xWall + TRIGGER_X[0] && v.x < xWall + TRIGGER_X[1] &&
      v.y > d.bayY0 - TRIGGER_MARGIN_Y && v.y < d.bayY1 + TRIGGER_MARGIN_Y &&
      v.z > TRIGGER_Z[0] && v.z < TRIGGER_Z[1]
  }

  _inOpening(d, camera) {
    const v = this._local(d, camera.position, new THREE.Vector3())
    const xWall = this._wallPlaneX(d)
    return Math.abs(v.x - xWall) < 1.0 &&
      v.y > d.bayY0 - 0.4 && v.y < d.bayY1 + 0.4 &&
      v.z > 0 && v.z < 3.0
  }

  _leafBox(d, outMin, outMax) {
    if (!d.leaf) return null
    d.leaf.updateMatrixWorld(true)
    const b = new THREE.Box3().setFromObject(d.leaf)
    outMin.set(b.min.x - OBSTRUCT_MARGIN, b.min.y - OBSTRUCT_MARGIN,
      b.min.z - OBSTRUCT_MARGIN)
    outMax.set(b.max.x + OBSTRUCT_MARGIN, b.max.y + OBSTRUCT_MARGIN,
      b.max.z + OBSTRUCT_MARGIN)
    return [outMin, outMax]
  }

  _obstructed(d, camera) {
    if (this._inOpening(d, camera)) return true
    const m = this._leafBox(d, new THREE.Vector3(), new THREE.Vector3())
    if (!m) return false
    const p = camera.position
    return p.x > m[0].x && p.x < m[1].x && p.y > m[0].y && p.y < m[1].y &&
      p.z > m[0].z && p.z < m[1].z
  }

  // Physical enter/exit at the wall plane: the camera is never moved; the
  // room state, collider set and lamp follow the crossing instead. Entering
  // means stepping from the street side (x < plane) through the plane into
  // the building; exiting is the reverse. The comparisons are inclusive so a
  // camera stepping 0.14 m per frame cannot skip the edge by landing exactly
  // on it, and the deadband on both sides stops a camera idling on the plane
  // from flipping the state every frame.
  _crossing(d, camera) {
    if (!this.active || this.paused || this.corridor?.active) return
    const v = this._local(d, camera.position, new THREE.Vector3())
    const plane = this._wallPlaneX(d)
    const prev = d.prevLocalX
    d.prevLocalX = v.x
    if (prev == null) return
    if (Math.abs(v.y - d.bayCenter) > 1.3 || v.z < 0 || v.z > 3.0) return
    const m = ENTER_MARGIN
    const inside = this.interiors.inside === d.room
    if (!inside && prev < plane - m && v.x >= plane - m) {
      this.interiors.enterPhysical(d.room)
      d.inside = true
    } else if (inside && prev > plane + m && v.x <= plane + m) {
      this.interiors.exitPhysical()
      d.inside = false
    }
  }

  // Interior zone preloading: the room and its lamp come up while the player
  // is still outside the threshold, so the opening never frames a black void.
  // Distances are measured from the wall plane, not the room origin — the HQ
  // threshold sits 4.9 m in front of its room.
  _preload(camera) {
    if (this.corridor?.active || this.paused) return
    if (this.interiors.inside) {
      this._lampTarget = this.interiors.inside.lamp ?? 1.9
      return
    }
    let nearest = null
    let nd = Infinity
    for (const d of this.doors) {
      if (!d.group) continue
      const c = this._local(d, camera.position, new THREE.Vector3())
      const dist = Math.hypot(c.x - this._wallPlaneX(d), c.y - d.bayCenter)
      if (dist < nd) { nd = dist; nearest = d }
    }
    let target = 0
    if (nearest && nd < PRELOAD_R) {
      nearest.room.group.visible = true
      target = 0.55
    }
    for (const d of this.doors) {
      if (this.interiors.inside === d.room || !d.room.group.visible) continue
      const c = this._local(d, camera.position, new THREE.Vector3())
      if (Math.hypot(c.x - this._wallPlaneX(d), c.y - d.bayCenter) >
          PRELOAD_R + 3) {
        d.room.group.visible = false
      }
    }
    this._lampTarget = target
  }

  _rampLamp(dt) {
    const lamp = this.interiors.lamp
    const cur = lamp.intensity
    const target = this._lampTarget
    if (Math.abs(cur - target) < 0.01) return
    const step = 1.4 * dt
    lamp.intensity = cur < target
      ? Math.min(target, cur + step)
      : Math.max(target, cur - step)
  }

  // ---- the state machine --------------------------------------------------

  _setState(d, state) {
    if (d.state === state) return
    d.state = state
    d.dwell = 0
    this._save()
    if (state === 'opening' || state === 'closing') this._swish(d)
  }

  _swish(d) {
    if (!this._audio) return
    const now = performance.now()
    if (now - d.soundAt > 500) {
      d.soundAt = now
      this._audio.doorSwish()
    }
  }

  _save() {
    const state = {}
    for (const d of this.doors) {
      if (d.state !== 'closed') state[d.key] = d.state
    }
    try {
      localStorage.setItem(SAVE_KEY, JSON.stringify({
        v: 1, doors: state, at: Date.now(),
      }))
    } catch { /* storage unavailable: door state simply does not persist */ }
  }

  _loadSaved() {
    try {
      const raw = localStorage.getItem(SAVE_KEY)
      return raw ? JSON.parse(raw) : null
    } catch { return null }
  }

  update(dt, camera) {
    if (!this.ready) return this.stats
    if (this.corridor?.active) {
      this.stats.state = 'corridor'
      return this.stats
    }
    if (this.paused) {
      this.stats.state = 'paused'
      return this.stats
    }
    if (this._ride) {
      this._rideStep(dt)
      this.stats.state = 'lift'
      return this.stats
    }
    this._preload(camera)
    this._rampLamp(dt)

    let open = 0
    for (const d of this.doors) {
      if (!d.group) continue
      if (!d.cut || !this._meshLive(d)) {
        const c = this._local(d, camera.position, new THREE.Vector3())
        if (c.length() < CUT_R) this._findAndCut(d)
      }
      const c = this._local(d, camera.position, new THREE.Vector3())
      d.near = Math.hypot(c.x - this._wallPlaneX(d), c.y - d.bayCenter) < 14

      const inTrigger = this._inTrigger(d, camera)
      d.trigger = inTrigger
      this._crossing(d, camera)

      switch (d.state) {
        case 'closed':
          if (inTrigger) this._setState(d, 'opening')
          break
        case 'opening':
          d.progress = Math.min(1, d.progress + dt / OPEN_S)
          if (d.progress >= 1) this._setState(d, 'open')
          break
        case 'open':
          d.dwell += dt
          if (!inTrigger && d.dwell > DWELL_S) this._setState(d, 'closing')
          break
        case 'closing':
          if (inTrigger || this._obstructed(d, camera)) {
            this._setState(d, 'opening')     // never close on the player
            break
          }
          d.progress = Math.max(0, d.progress - dt / CLOSE_S)
          if (d.progress <= 0) this._setState(d, 'closed')
          break
      }
      if (d.state === 'open') open++
      if (d.leaf) {
        d.leaf.position.y = d.bayY0 + 0.02 + d.progress * LEAF_W
        // Push the new position into the world matrix now. Raycasting does
        // not update matrices — it trusts them — and the walk collider probes
        // this leaf in the *same* frame the door moves. Without this the
        // collider sees wherever the leaf was at the last render, which under
        // the QA harness (render loop frozen) means it never moves at all:
        // measured, the leaf blocked the walk-in on 160 of 181 frames with
        // the door reading fully open.
        d.group.updateMatrixWorld(true)
      }
    }
    this.stats.open = open
    this.stats.state = open ? 'open' : 'closed'
    return this.stats
  }

  // Meshes the walk collider should test near this door.
  pickables() {
    const out = []
    for (const d of this.doors) {
      if (d.group && (d.near || this.interiors.inside === d.room)) {
        out.push(d.group)
      }
    }
    return out
  }

  // How far the camera is into a threshold (0..1) — feeds the audio mix.
  indoorBlend(camera) {
    let best = 0
    for (const d of this.doors) {
      if (!d.group) continue
      const c = this._local(d, camera.position, new THREE.Vector3())
      const plane = this._wallPlaneX(d)
      const dx = Math.abs(c.x - plane)
      if (dx < 1.2 && Math.abs(c.y - d.bayCenter) < 1.5 && c.z > 0 && c.z < 3) {
        best = Math.max(best, 1 - dx / 1.2)
      }
    }
    return best
  }

  // ---- physical lift rides -------------------------------------------------

  // E at a lift link becomes a ride in the corridor's own cab: the camera
  // travels the shaft and the arrival is placed at the room's authored shot,
  // not a jump from one building to another.
  rideLift(link, camera, controls) {
    if (this.corridor?.active || this.paused || this._ride) return false
    const from = this.interiors.inside
    const to = link && link.room
    const cab = this.corridor && this.corridor.lift
    if (!from || !to || !cab) return false
    this._ride = {
      cab, camera, controls, from, to,
      t: 0,
      dur: 1.4 + Math.abs(from.local(2, 0, 0).y - to.local(2, 0, 0).y) / 26.0,
      y0: from.local(2, 0, 0).y,
      y1: to.local(2, 0, 0).y,
      yaw: from.yaw,
    }
    const p = from.local(2, 0, 0)
    cab.position.set(p.x, p.y, p.z)
    cab.rotation.set(0, from.yaw, 0)
    cab.visible = true
    cab.updateMatrixWorld(true)
    this.interiors.lamp.intensity = 1.6
    this._rideLook(camera, controls, cab)
    return true
  }

  _rideLook(camera, controls, cab) {
    cab.updateMatrixWorld(true)
    camera.position.copy(
      cab.localToWorld(new THREE.Vector3(1.15, 1.7, 0)))
    camera.lookAt(cab.localToWorld(new THREE.Vector3(-3.0, 1.45, 0)))
    const e = new THREE.Euler().setFromQuaternion(camera.quaternion, 'YXZ')
    if (controls) { controls.yaw = e.y; controls.pitch = e.x }
  }

  _rideStep(dt) {
    const r = this._ride
    if (!r) return
    r.t += dt
    const u = Math.min(1, r.t / r.dur)
    const s = u * u * (3 - 2 * u)
    r.cab.position.y = r.y0 + (r.y1 - r.y0) * s
    r.cab.updateMatrixWorld(true)
    this._rideLook(r.camera, r.controls, r.cab)
    if (u >= 1) {
      const to = r.to
      r.cab.visible = false
      this.interiors.enterPhysical(to)
      this._ride = null
      if (to.shot) {
        r.camera.position.copy(to.shot.eye)
        r.camera.lookAt(to.shot.at)
        const e = new THREE.Euler().setFromQuaternion(
          r.camera.quaternion, 'YXZ')
        if (r.controls) { r.controls.yaw = e.y; r.controls.pitch = e.x }
      }
    }
  }

  // ---- verification --------------------------------------------------------
  // Measured, per HANDOFF §0. Each check returns numbers; the headless runner
  // applies the thresholds (scripts/qa/doorcheck-run.mjs).

  verify() {
    const out = { ok: true, checks: [] }
    const say = (name, ok, d) => {
      out.checks.push({ name, ok, ...d })
      if (!ok) out.ok = false
    }

    for (const d of this.doors) {
      if (!d.group) {
        say(`${d.key} placed`, false, { reason: 'no assembly group' })
        continue
      }
      // The glaze counts are the "no missing wall" evidence: a doorway leaves
      // glass standing either side of the opening (glazeKept > 0), it does
      // not delete the pane.
      say(`${d.key} placed`, true, {
        state: d.state, kind: d.kind, bid: d.bid,
        wallDist_m: +(d.wallDist ?? -1).toFixed(2),
        relocated: !!d.relocated, shifted: !!d.shifted,
        frontagePasses: d.frontagePasses ?? null,
        shiftResidual_m: d.shiftResidual_m ?? null, cutWhy: d.cutWhy,
        cutFaces: d.cutFaces, removedTris: d.removedTris,
        passageRemoved: d.passageRemoved,
        passageCutFaces: d.passageCutFaces,
        passageBoxRemoved: d.passageBoxRemoved,
        glazeCutFaces: d.glazeCut, glazeRemovedTris: d.glazeRemoved,
        glazeTrisKept: d.glazeKept,
        assembly: this._assemblyMetrics(d),
        lastClear: d.lastClear,
      })

      const res = this._probeOpening(d)
      say(`${d.key} opening is real (render)`, res.blocked === 0, {
        rays: res.rays, blocked: res.blocked,
        wallCut: d.cut, cutFaces: d.cutFaces,
        wallDist_m: +(d.wallDist ?? -1).toFixed(2),
      })

      const walk = this._walkTest(d, 1)
      say(`${d.key} walk-in crosses without teleport`,
        walk.crossed && walk.maxJump < 0.5 && walk.inside,
        { maxJump_m: +walk.maxJump.toFixed(3), frames: walk.frames,
          crossed: walk.crossed, inside: walk.inside,
          startLocalX: walk.startLocalX, endLocalX: walk.endLocalX,
          doorState: walk.doorState, maxJumpAt: walk.maxJumpAt })

      const rev = this._walkTest(d, -1)
      say(`${d.key} reverse traversal exits`,
        rev.crossed && !rev.inside,
        { maxJump_m: +rev.maxJump.toFixed(3), frames: rev.frames,
          crossed: rev.crossed, inside: rev.inside,
          startLocalX: rev.startLocalX, endLocalX: rev.endLocalX,
          doorState: rev.doorState, maxJumpAt: rev.maxJumpAt })

      const cyc = this._cycleTest(d)
      say(`${d.key} door cycle opens and closes`, cyc.openCycles >= 2 &&
        cyc.closedOnce, cyc)

      const obs = this._obstructionTest(d)
      say(`${d.key} obstruction reopens`, obs.reopened, obs)

      const pre = this._preloadTest(d)
      say(`${d.key} interior preloads`, pre.visible && pre.lamp > 0.2, pre)
    }

    const pause = this._pauseTest()
    say('pause freezes the door machine', pause.frozen, pause)

    return out
  }

  // Is the assembly standing up the way it was authored? The frame convention
  // error this file shipped with was invisible to every behavioural check —
  // the door still cycled, the trigger still fired — but it laid the assembly
  // on its side. These three numbers catch it without a render: a door leaf
  // is taller than it is wide, and the lit panel is overhead.
  _assemblyMetrics(d) {
    if (!d.leaf || !d.group) return null
    d.group.updateMatrixWorld(true)
    const leaf = new THREE.Box3().setFromObject(d.leaf)
    const panel = d.group.getObjectByName('authored')
    const lit = panel ? panel.children[panel.children.length - 1] : null
    const litBox = lit ? new THREE.Box3().setFromObject(lit) : null
    const floor = this.roomToWorld(d, 0, d.bayCenter, 0).y
    return {
      leafHeight_m: +(leaf.max.y - leaf.min.y).toFixed(2),
      leafWidth_m: +Math.max(leaf.max.x - leaf.min.x,
        leaf.max.z - leaf.min.z).toFixed(2),
      litPanelAboveFloor_m: litBox
        ? +(litBox.min.y - floor).toFixed(2) : null,
    }
  }

  // Rays through the door rect from the street side at eye height, against
  // the city meshes plus the HQ tower. Any hit before the room (wall band
  // region) means the opening is not actually there. The hits' object names
  // and building ids are recorded so a blocked ray says *what* blocked it.
  _probeOpening(d) {
    const raycaster = new THREE.Raycaster()
    let blocked = 0
    const dir = this._doorDir(d)
    const plane = this._wallPlaneX(d)
    const cols = 5
    const rows = 3
    const rays = []
    const colliders = [...this.streamer.pickables()]
    if (this.hq && this.hq.tower) colliders.push(this.hq.tower.children[0])
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        const y = d.bayY0 + (c + 0.5) / cols * (d.bayY1 - d.bayY0)
        const z = 1.2 + r / rows * 1.1
        const origin = this.roomToWorld(d, plane - 2.0, y, z)
        raycaster.set(origin, dir)
        // 2 m of approach, the wall itself, and the depth of the room behind
        // it. Anything solid before the room's own back wall means the
        // opening is not there. The window is measured from the door plane,
        // not a fixed 3.8 m: the HQ's plane was 4.5 m out of position and a
        // fixed window let a solid podium wall 6.5 m in count as clear.
        raycaster.far = ROOM_DEPTH_PROBE
        const hit = raycaster.intersectObjects(colliders, true)[0]
        const blockedHere = !!hit && hit.distance < 2.0 + PROBE_CLEAR
        if (blockedHere) blocked++
        rays.push({
          hit: blockedHere,
          distance: hit ? +hit.distance.toFixed(2) : null,
          object: hit && hit.object ? hit.object.name || hit.object.type : null,
          bid: hit && hit.object && hit.object.geometry &&
            (hit.object.geometry.attributes._bid ||
             hit.object.geometry.attributes._BID)
            ? Math.round((hit.object.geometry.attributes._bid ||
                hit.object.geometry.attributes._BID).getX(
                  hit.face ? hit.face.a : 0)) : null,
        })
      }
    }
    return { rays: rays.length, blocked, rays }
  }

  // Drive the camera straight through the doorway with the real walk
  // controls (keys + controls.update), recording position continuity.
  // dir +1 = street to room, -1 = room to street. The collider set is
  // refreshed every step so the door assembly joins it as the player closes
  // in (the render loop is frozen by the QA runner during these tests).
  // opts.trace collects the sampled camera positions, so the runner can
  // prove determinism by replaying the identical walk twice.
  _walkTest(d, dir, opts = {}) {
    const camera = this._camera
    const controls = this._controls
    if (!camera || !controls) {
      return { crossed: false, maxJump: 1e9, frames: 0, inside: false }
    }
    const colliders = () => {
      const list = [...this.streamer.pickables()]
      for (const g of this.pickables()) list.push(g)
      if (this.hq && this.hq.tower) list.push(this.hq.tower.children[0])
      controls.setColliders(list)
    }
    const plane = this._wallPlaneX(d)
    if (dir < 0) this.interiors.enterPhysical(d.room)
    // Start outside the trigger's reach so the walk includes the approach the
    // door's timing is built around, rather than beginning on top of it.
    const start = this.roomToWorld(d, plane - dir * WALK_START, d.bayCenter, 1.7)
    const target = this.roomToWorld(d, plane + dir * 3.0, d.bayCenter, 1.7)
    camera.position.copy(start)
    controls.mode = 'walk'
    const dx = target.x - start.x
    const dz = target.z - start.z
    // world forward for yaw is (-sin yaw, 0, -cos yaw); solve for the
    // direction that points at the doorway
    controls.yaw = Math.atan2(-dx, -dz)
    controls.pitch = 0
    camera.quaternion.setFromEuler(new THREE.Euler(0, controls.yaw, 0, 'YXZ'))
    controls.keys.add('KeyW')
    let maxJump = 0
    let maxJumpAt = null
    let prev = camera.position.clone()
    let crossed = false
    let reachedInside = this.interiors.inside === d.room
    const frames = 180
    const dt = 1 / 30
    const lp = new THREE.Vector3()
    const trace = opts.trace ? [] : null
    let prevVX = null
    let i = 0
    const m = ENTER_MARGIN
    for (; i < frames; i++) {
      colliders()
      this.update(dt, camera)
      controls.update(dt)
      // crossing mirrors _crossing's deadband: the camera has to move
      // through the plane band, not merely start on the far side of it
      const v = this._local(d, camera.position, lp)
      if (i >= 5) {
        // skip the first frames: gravity settles the eye onto the ground
        if (prevVX != null) {
          const goingIn = dir > 0 &&
            prevVX < plane - m && v.x >= plane - m
          const goingOut = dir < 0 &&
            prevVX > plane + m && v.x <= plane + m
          if (goingIn || goingOut) crossed = true
        }
        prevVX = v.x
      }
      if (trace && i >= 5) trace.push([+camera.position.x.toFixed(3),
        +camera.position.y.toFixed(3), +camera.position.z.toFixed(3)])
      const jump = camera.position.distanceTo(prev)
      if (i >= 5 && jump > maxJump) {
        maxJump = jump
        let groundHit = null
        const gr = new THREE.Raycaster(
          new THREE.Vector3(camera.position.x, camera.position.y + 1,
            camera.position.z),
          new THREE.Vector3(0, -1, 0), 0, 600)
        const gh = gr.intersectObjects(controls.colliders, true)[0]
        if (gh) {
          const attr = gh.object.geometry.attributes._bid ||
            gh.object.geometry.attributes._BID
          groundHit = {
            y: +gh.point.y.toFixed(2),
            obj: gh.object.name || gh.object.type,
            bid: attr ? Math.round(attr.getX(gh.face ? gh.face.a : 0)) : null,
          }
        }
        // every collider mesh whose AABB crosses the vertical segment below
        // the camera — the definitive list of what could be underfoot
        const under = []
        for (const c of controls.colliders) {
          c.traverse((o) => {
            if (!o.isMesh) return
            const g = o.geometry
            if (!g.boundingBox) g.computeBoundingBox()
            const b = g.boundingBox
            const px = camera.position.x
            const pz = camera.position.z
            if (px > b.min.x && px < b.max.x && pz > b.min.z &&
                pz < b.max.z && b.max.y > 11.9) {
              under.push({
                obj: o.name || o.type,
                y: [+b.min.y.toFixed(1), +b.max.y.toFixed(1)],
              })
            }
          })
        }
        maxJumpAt = {
          frame: i,
          from: [prev.x, prev.y, prev.z].map((v) => +v.toFixed(3)),
          to: [camera.position.x, camera.position.y, camera.position.z]
            .map((v) => +v.toFixed(3)),
          doorState: d.state,
          leafY: d.leaf ? +d.leaf.position.y.toFixed(3) : null,
          groundHit,
          under,
        }
      }
      prev.copy(camera.position)
      reachedInside = this.interiors.inside === d.room
      // the crossing fires at the plane boundary; the walk is complete once
      // the room state has actually flipped (a few frames later)
      const done = crossed && (dir > 0 ? reachedInside : !reachedInside)
      if (done) break
    }
    controls.keys.delete('KeyW')
    this.interiors.exitPhysical()
    for (const r of this.doors) {
      if (r.room.group.visible) r.room.group.visible = false
    }
    this._lampTarget = 0
    this.interiors.lamp.intensity = 0
    return { crossed, maxJump, maxJumpAt, frames: i + 1, inside: reachedInside,
      doorState: d.state, trace,
      startLocalX: +(plane - dir * WALK_START).toFixed(2),
      endLocalX: +this._local(d, camera.position, lp).x.toFixed(2) }
  }

  _cycleTest(d) {
    const camera = this._camera
    if (!camera) return { openCycles: 0, closedOnce: false, reason: 'no camera' }
    const plane = this._wallPlaneX(d)
    // "away" has to be clear of the trigger's reach, or the door never gets
    // the chance to close and the cycle test measures nothing
    const outside = this.roomToWorld(d, plane + TRIGGER_X[0] - 3,
      d.bayCenter, 1.7)
    const atDoor = this.roomToWorld(d, plane - 0.6, d.bayCenter, 1.7)
    let openCycles = 0
    let closedOnce = false
    const step = (pos, frames) => {
      camera.position.copy(pos)
      for (let i = 0; i < frames; i++) {
        this.update(1 / 30, camera)
      }
    }
    // arrive, wait for the door to open, leave, wait for it to close -- twice
    step(outside, 5)
    step(atDoor, 90)
    if (d.state === 'open') openCycles = 1
    step(outside, 240)
    if (d.state === 'closed') closedOnce = true
    step(atDoor, 90)
    if (d.state === 'open') openCycles++
    step(outside, 240)
    if (d.state === 'closed') closedOnce = true
    this.interiors.exitPhysical()
    return { openCycles, closedOnce }
  }

  _obstructionTest(d) {
    const camera = this._camera
    if (!camera) return { reopened: false, reason: 'no camera' }
    const plane = this._wallPlaneX(d)
    const at = this.roomToWorld(d, plane - 0.1, d.bayCenter, 1.2)
    camera.position.copy(at)
    d.trigger = false
    this._setState(d, 'closed')
    this._setState(d, 'opening')
    for (let i = 0; i < 40; i++) this.update(1 / 30, camera)
    // the player is still inside the opening: force a close and expect reopen
    d.trigger = false
    this._setState(d, 'closing')
    d.progress = 0.2
    let reopened = false
    for (let i = 0; i < 40; i++) {
      this.update(1 / 30, camera)
      if (d.state === 'opening') { reopened = true; break }
    }
    this.interiors.exitPhysical()
    d.trigger = false
    this._setState(d, 'closed')
    return { reopened, state: d.state }
  }

  _preloadTest(d) {
    const camera = this._camera
    if (!camera) return { visible: false, lamp: 0, reason: 'no camera' }
    const plane = this._wallPlaneX(d)
    const at = this.roomToWorld(d, plane - 7, d.bayCenter, 1.7)
    camera.position.copy(at)
    for (let i = 0; i < 20; i++) this.update(1 / 30, camera)
    const lamp = this.interiors.lamp.intensity
    const visible = d.room.group.visible
    this.interiors.exitPhysical()
    for (const r of this.doors) {
      if (r.room.group.visible) r.room.group.visible = false
    }
    this._lampTarget = 0
    this.interiors.lamp.intensity = 0
    return { visible, lamp: +lamp.toFixed(2) }
  }

  _pauseTest() {
    const d = this.doors.find((x) => x.group)
    if (!d) return { frozen: false, reason: 'no doors' }
    const before = d.progress
    this.paused = true
    for (let i = 0; i < 40; i++) this.update(1 / 30, this._camera)
    const frozen = d.progress === before
    this.paused = false
    return { frozen, before, after: d.progress }
  }
}
