/**
 * Four loaded sportback tiers, worn by every car in the registry.
 *
 * VehicleRig builds nine procedural primitives per vehicle — the 101 boxes and
 * cylinders placeholdercheck fails on. Replacing them with authored geometry
 * raises a question the primitive version never had to answer: what is shared
 * between cars and what is not.
 *
 * Geometry is shared. Eleven cars pointing at one set of buffers is the whole
 * reason a pool exists; cloning geometry per car would put eleven copies of the
 * same 2,816 triangles on the GPU for no visual difference.
 *
 * Light materials are **not** shared. Each car brakes on its own schedule, and
 * `emissiveIntensity` lives on the material — so a shared brake material means
 * every car in Manhattan lights up when any one of them slows down. That is the
 * kind of bug that looks like a shader problem and is an ownership problem.
 *
 * Paint is not shared either, because the fleet is coloured by kind: a taxi and
 * a police car cannot be the same material instance.
 *
 * So an instance owns two or three materials and borrows everything else, and
 * release disposes exactly what it owns. Disposing a borrowed material would
 * blank every other car.
 */
import * as THREE from 'three'

import {
  bindVehicleAsset,
  validateVehicleAsset,
  type BoundVehicle,
} from './vehicle-asset'

/** Where the tiers live. Generated by scripts/assets/build-vehicle.mjs. */
export const SPORTBACK_LOD0 = '/models/vehicles/sportback_lod0.glb'
export const SPORTBACK_LOD1 = '/models/vehicles/sportback_lod1.glb'
export const SPORTBACK_LOD2 = '/models/vehicles/sportback_lod2.glb'
export const SPORTBACK_LOD3 = '/models/vehicles/sportback_lod3.glb'

/**
 * Screen-space tiers for the fleet.
 *
 * LOD0/1 retain the complete wheel-and-light contract. LOD2 keeps wheels but
 * drops the lenses, and LOD3 is deliberately only a traffic silhouette. The
 * distances are close enough that the real street population uses every tier
 * rather than shipping dormant files in `public/`.
 */
export const SPORTBACK_LODS = [
  { url: SPORTBACK_LOD0, distance: 0, fullContract: true },
  { url: SPORTBACK_LOD1, distance: 45, fullContract: true },
  { url: SPORTBACK_LOD2, distance: 110, fullContract: false },
  { url: SPORTBACK_LOD3, distance: 220, fullContract: false },
] as const

/** Body colour per vehicle kind. Unbranded; a taxi is yellow everywhere. */
const PAINT: Record<string, string> = {
  sedan: '#c8c4b8',
  taxi: '#f2b632',
  police: '#24344f',
  ambulance: '#e9eef2',
}

export interface VehicleInstance {
  kind: string
  /** Near-tier binding, kept as the canonical interaction contract. */
  bound: BoundVehicle
  /** Every tier that has runtime-driven parts (far silhouettes are harmless). */
  bindings: BoundVehicle[]
  group: THREE.LOD
  /** Materials this instance created and must dispose. */
  owned: THREE.Material[]
}

export interface GltfSource {
  loadAsync(url: string): Promise<{ scene: THREE.Group }>
}

/**
 * Clone a subtree, sharing geometry and replacing named materials with
 * per-instance copies.
 *
 * `THREE.Object3D.clone()` shares both geometry and materials by reference,
 * which is right for one and wrong for the other. The materials that have to be
 * unique are copied here, once, rather than deep-cloning everything.
 */
function cloneWithOwnMaterials(
  source: THREE.Object3D,
  shouldOwn: (material: THREE.Material) => boolean,
  owned: THREE.Material[],
): THREE.Object3D {
  const copy = source.clone(true)
  const replacements = new Map<THREE.Material, THREE.Material>()
  copy.traverse((object) => {
    if (!(object instanceof THREE.Mesh)) return
    const list = Array.isArray(object.material) ? object.material : [object.material]
    const next = list.map((material) => {
      if (!material || !shouldOwn(material)) return material
      const existing = replacements.get(material)
      if (existing) return existing
      const replacement = material.clone()
      replacements.set(material, replacement)
      owned.push(replacement)
      return replacement
    })
    object.material = Array.isArray(object.material) ? next : next[0]
  })
  return copy
}

/** A material whose emissive the runtime drives, or the body paint. */
function isPerCarMaterial(material: THREE.Material): boolean {
  return /^VEH_(lamp_|paint)/.test(material.name)
}

export class VehicleAssetPool {
  private templates: THREE.Group[] | null = null
  private loading: Promise<THREE.Group | null> | null = null
  private failure: string | null = null

  /** Whether a car can be dressed in authored geometry right now. */
  get ready(): boolean {
    return this.templates !== null
  }

  /** Why the asset is unavailable, or null. */
  get error(): string | null {
    return this.failure
  }

  /**
   * Load all four tiers once.
   *
   * Idempotent and safe to call from a frame callback: the second caller gets
   * the first caller's promise rather than starting a second fetch.
   */
  load(loader: GltfSource): Promise<THREE.Group | null> {
    if (this.templates) return Promise.resolve(this.templates[0])
    if (this.loading) return this.loading
    this.loading = Promise.all(SPORTBACK_LODS.map(({ url }) => loader.loadAsync(url)))
      .then((loaded) => {
        const templates = loaded.map(({ scene }) => scene)
        for (let i = 0; i < templates.length; i++) {
          const tier = SPORTBACK_LODS[i]
          const probe = bindVehicleAsset(templates[i].clone(true))
          const hasGeometry = probe.root.getObjectByProperty('isMesh', true) !== undefined
          const problems = tier.fullContract
            ? validateVehicleAsset(probe).map((p) => p.problem)
            : hasGeometry
              ? []
              : ['asset contains no meshes']
          if (problems.length > 0) {
            this.failure = `${tier.url}: ${problems.join('; ')}`
            return null
          }
        }
        this.templates = templates
        return templates[0]
      })
      .catch((err: unknown) => {
        this.failure = err instanceof Error ? err.message : String(err)
        return null
      })
    return this.loading
  }

  /**
   * Dress one car.
   *
   * Returns null when the asset is not loaded, which is a normal state for the
   * first few frames — the caller falls back to the procedural rig rather than
   * rendering nothing.
   */
  acquire(kind: string): VehicleInstance | null {
    if (!this.templates) return null
    const owned: THREE.Material[] = []
    const group = new THREE.LOD()
    group.name = `VEH_${kind}`
    const bindings: BoundVehicle[] = []

    for (let i = 0; i < this.templates.length; i++) {
      const copy = cloneWithOwnMaterials(
        this.templates[i],
        isPerCarMaterial,
        owned,
      ) as THREE.Group
      copy.name = `VEH_${kind}_LOD${i}`
      bindings.push(bindVehicleAsset(copy))
      group.addLevel(copy, SPORTBACK_LODS[i].distance)
    }

    for (const material of owned) {
      if (material.name.startsWith('VEH_paint')) {
        const colour = PAINT[kind] ?? PAINT.sedan
        ;(material as THREE.MeshStandardMaterial).color = new THREE.Color(colour)
      }
      // Lights start dark; the rig raises them from the simulation's flags.
      if (material.name.startsWith('VEH_lamp')) {
        ;(material as THREE.MeshStandardMaterial).emissiveIntensity = 0
      }
    }

    return { kind, bound: bindings[0], bindings, group, owned }
  }

  /**
   * Give a car back.
   *
   * Only the per-instance materials are disposed. The geometry and the shared
   * materials belong to the template and outlive every car that wore them —
   * disposing those here would blank the rest of the fleet.
   */
  release(instance: VehicleInstance): void {
    for (const material of instance.owned) material.dispose()
    instance.owned.length = 0
    instance.group.removeFromParent()
  }

  /** Release the template itself. For teardown. */
  dispose(): void {
    if (this.templates) {
      const geometries = new Set<THREE.BufferGeometry>()
      const materials = new Set<THREE.Material>()
      for (const template of this.templates) {
        template.traverse((object) => {
          if (!(object instanceof THREE.Mesh)) return
          geometries.add(object.geometry)
          const list = Array.isArray(object.material) ? object.material : [object.material]
          for (const material of list) if (material) materials.add(material)
        })
      }
      for (const geometry of geometries) geometry.dispose()
      for (const material of materials) material.dispose()
    }
    this.templates = null
    this.loading = null
    this.failure = null
  }
}

/** The game's pool. One asset, one fetch, every car. */
export const vehicleAssetPool = new VehicleAssetPool()
