/**
 * One loaded sportback, worn by every car in the registry.
 *
 * VehicleRig builds nine procedural primitives per vehicle — the 101 boxes and
 * cylinders placeholdercheck fails on. Replacing them with authored geometry
 * raises a question the primitive version never had to answer: what is shared
 * between cars and what is not.
 *
 * Geometry is shared. Eleven cars pointing at one set of buffers is the whole
 * reason a pool exists; cloning geometry per car would put eleven copies of the
 * same 2,816 triangles on the GPU for no visual difference.
 *
 * Light materials are **not** shared. Each car brakes on its own schedule, and
 * `emissiveIntensity` lives on the material — so a shared brake material means
 * every car in Manhattan lights up when any one of them slows down. That is the
 * kind of bug that looks like a shader problem and is an ownership problem.
 *
 * Paint is not shared either, because the fleet is coloured by kind: a taxi and
 * a police car cannot be the same material instance.
 *
 * So an instance owns two or three materials and borrows everything else, and
 * release disposes exactly what it owns. Disposing a borrowed material would
 * blank every other car.
 */
import * as THREE from 'three'

import {
  bindVehicleAsset,
  validateVehicleAsset,
  type BoundVehicle,
} from './vehicle-asset'

/** Where the tiers live. Generated by scripts/assets/build-vehicle.mjs. */
export const SPORTBACK_LOD0 = '/models/vehicles/sportback_lod0.glb'
export const SPORTBACK_LOD1 = '/models/vehicles/sportback_lod1.glb'

/** Body colour per vehicle kind. Unbranded; a taxi is yellow everywhere. */
const PAINT: Record<string, string> = {
  sedan: '#c8c4b8',
  taxi: '#f2b632',
  police: '#24344f',
  ambulance: '#e9eef2',
}

export interface VehicleInstance {
  kind: string
  bound: BoundVehicle
  group: THREE.Group
  /** Materials this instance created and must dispose. */
  owned: THREE.Material[]
}

export interface GltfSource {
  loadAsync(url: string): Promise<{ scene: THREE.Group }>
}

/**
 * Clone a subtree, sharing geometry and replacing named materials with
 * per-instance copies.
 *
 * `THREE.Object3D.clone()` shares both geometry and materials by reference,
 * which is right for one and wrong for the other. The materials that have to be
 * unique are copied here, once, rather than deep-cloning everything.
 */
function cloneWithOwnMaterials(
  source: THREE.Object3D,
  shouldOwn: (material: THREE.Material) => boolean,
  owned: THREE.Material[],
): THREE.Object3D {
  const copy = source.clone(true)
  const replacements = new Map<THREE.Material, THREE.Material>()
  copy.traverse((object) => {
    if (!(object instanceof THREE.Mesh)) return
    const list = Array.isArray(object.material) ? object.material : [object.material]
    const next = list.map((material) => {
      if (!material || !shouldOwn(material)) return material
      const existing = replacements.get(material)
      if (existing) return existing
      const replacement = material.clone()
      replacements.set(material, replacement)
      owned.push(replacement)
      return replacement
    })
    object.material = Array.isArray(object.material) ? next : next[0]
  })
  return copy
}

/** A material whose emissive the runtime drives, or the body paint. */
function isPerCarMaterial(material: THREE.Material): boolean {
  return /^VEH_(lamp_|paint)/.test(material.name)
}

export class VehicleAssetPool {
  private template: THREE.Group | null = null
  private loading: Promise<THREE.Group | null> | null = null
  private failure: string | null = null

  /** Whether a car can be dressed in authored geometry right now. */
  get ready(): boolean {
    return this.template !== null
  }

  /** Why the asset is unavailable, or null. */
  get error(): string | null {
    return this.failure
  }

  /**
   * Load the near tier once.
   *
   * Idempotent and safe to call from a frame callback: the second caller gets
   * the first caller's promise rather than starting a second fetch.
   */
  load(loader: GltfSource, url = SPORTBACK_LOD0): Promise<THREE.Group | null> {
    if (this.template) return Promise.resolve(this.template)
    if (this.loading) return this.loading
    this.loading = loader
      .loadAsync(url)
      .then(({ scene }) => {
        // Validated on arrival, not on first use. An asset that cannot be bound
        // should fail here, next to the URL that produced it, rather than
        // silently giving every car three wheels.
        const problems = validateVehicleAsset(bindVehicleAsset(scene.clone(true)))
        if (problems.length > 0) {
          this.failure = `${url}: ${problems.map((p) => p.problem).join('; ')}`
          return null
        }
        this.template = scene
        return scene
      })
      .catch((err: unknown) => {
        this.failure = `${url}: ${err instanceof Error ? err.message : String(err)}`
        return null
      })
    return this.loading
  }

  /**
   * Dress one car.
   *
   * Returns null when the asset is not loaded, which is a normal state for the
   * first few frames — the caller falls back to the procedural rig rather than
   * rendering nothing.
   */
  acquire(kind: string): VehicleInstance | null {
    if (!this.template) return null
    const owned: THREE.Material[] = []
    const copy = cloneWithOwnMaterials(this.template, isPerCarMaterial, owned) as THREE.Group
    copy.name = `VEH_${kind}`

    for (const material of owned) {
      if (material.name.startsWith('VEH_paint')) {
        const colour = PAINT[kind] ?? PAINT.sedan
        ;(material as THREE.MeshStandardMaterial).color = new THREE.Color(colour)
      }
      // Lights start dark; the rig raises them from the simulation's flags.
      if (material.name.startsWith('VEH_lamp')) {
        ;(material as THREE.MeshStandardMaterial).emissiveIntensity = 0
      }
    }

    const bound = bindVehicleAsset(copy)
    return { kind, bound, group: copy, owned }
  }

  /**
   * Give a car back.
   *
   * Only the per-instance materials are disposed. The geometry and the shared
   * materials belong to the template and outlive every car that wore them —
   * disposing those here would blank the rest of the fleet.
   */
  release(instance: VehicleInstance): void {
    for (const material of instance.owned) material.dispose()
    instance.owned.length = 0
    instance.group.removeFromParent()
  }

  /** Release the template itself. For teardown. */
  dispose(): void {
    if (this.template) {
      this.template.traverse((object) => {
        if (!(object instanceof THREE.Mesh)) return
        object.geometry.dispose()
        const list = Array.isArray(object.material) ? object.material : [object.material]
        for (const m of list) m?.dispose()
      })
    }
    this.template = null
    this.loading = null
    this.failure = null
  }
}

/** The game's pool. One asset, one fetch, every car. */
export const vehicleAssetPool = new VehicleAssetPool()
